### ISSUE TITLE
Disable verbosity

### ISSUE THREAD

**Issue by romancin** [xxxzc/xps15-9570-macos#10]
Hi! Is It possible to disable verbosity on Boot? I have been trying It but anything works. Thank you!

**Comment by xxxzc** [comment]
Remove `-v` in boot-args https://github.com/xxxzc/xps15-9570-macos/blob/018d809981c7429b369919a0f6f192d3650d72cd/OC/config.plist#L532

**Comment by romancin** [comment]
I already changed this, trying to solve It, changes to config.plist file seems to not be applied until I reset NVRAM. Is It normal?

**Comment by M69W** [comment]
> I already changed this, trying to solve It, changes to config.plist file seems to not be applied until I reset NVRAM. Is It normal?

have to reset NVRAM

**Comment by romancin** [comment]
Ok, thank you.
