### ISSUE TITLE
11.15下用python3 update更新了一下，然后直接设置升级到12.0.启动完毕后运行python3 update会x Neither CLOVER or OC was found.

### ISSUE THREAD

**Issue by luobingwei** [xxxzc/xps15-9570-macos#100]
python3 update.py --fixsleep
x Neither CLOVER or OC was found.

[xps9570@XPS9570deMBP OC %] python3 update.py --set rom=$(ifconfig en0 | awk '/ether/{print $2}' | sed -e 's/\://g')
x Neither CLOVER or OC was found.

**Comment by xxxzc** [comment]
我忘了更新链接了，你用的应该是master分支里的update.py。。下载repo里的update.py用吧，

https://github.com/xxxzc/xps15-9570-macos/blob/6bb31f72b0f5f62b784791c951c255eaa13052e2/update.py#L42

**Comment by luobingwei** [comment]
作者好，感谢做出这么好用的efi。
另外我每次重启均会出现Dell的BIOS白色背景警告。内容是
SupportAssist| Pre-Boot system Performance Check

Warning Message
Thunderbolt PCIe Device Enumeration Modes Has Switched To BIOS Assist.

**Comment by xxxzc** [comment]
> 作者好，感谢做出这么好用的efi。
> 另外我每次重启均会出现Dell的BIOS白色背景警告。内容是
> SupportAssist| Pre-Boot system Performance Check
> 
> Warning Message
> Thunderbolt PCIe Device Enumeration Modes Has Switched To BIOS Assist.

在bios里指定雷电的模式就不会有这个警告
