### ISSUE TITLE
problem about my Model Identifier

### ISSUE THREAD

**Issue by nguyenthienhoan** [xxxzc/xps15-9570-macos#102]
idon't know, please help me fix it to MacBookPro15,1

<img width="455" alt="Screen Shot 2022-01-09 at 23 43 45" src="https://user-images.githubusercontent.com/23251203/148691874-678b663d-75f0-480e-af43-457859e89763.png">

**Comment by nguyenthienhoan** [comment]
i was change it in config.plist, but still have this problem
<img width="235" alt="Screen Shot 2022-01-09 at 23 47 23" src="https://user-images.githubusercontent.com/23251203/148692010-a8ea7a5e-4fd7-47e6-bf02-d4f20a92a0ed.png">

**Comment by imraan-go** [comment]
You probably put a wrong serial number. Use **macserial** from opencore pkg to generate serial number for `MacbookPro15,1`
