### ISSUE TITLE
10.5版本经过多次测试在12上dw1830没有网络，替换驱动为之前的版本才行

### ISSUE THREAD

**Issue by xiaoli123** [xxxzc/xps15-9570-macos#108]
10.5版本经过多次测试在12上dw1830没有网络，替换驱动为之前的版本才行，测试很多次，重建缓存都不行

**Comment by xxxzc** [comment]
是只换了 AirportBrcmFixup.kext 到上一个版本吗，还是所有的kexts？有可能是我忘了把 IntelBTPatcher.kext 排除导致的

**Comment by xiaoli123** [comment]
都换了

**Comment by xiaoli123** [comment]
可以说下怎么处理吗？或者您处理下

**Comment by xxxzc** [comment]
麻烦试一下我新发的1006

**Comment by xiaoli123** [comment]
测试完了，10.15可以，12的话依旧不行，不知道什么问题

**Comment by xiaoli123** [comment]
测试时会清理缓存

**Comment by xxxzc** [comment]
我回去把dw1830换上试试，不好意思哈

**Comment by xiaoli123** [comment]
没事，应该感谢你分享，我们才能白嫖

**Comment by xxxzc** [comment]
我在macOS 13测了下DW1830是正常的，不需要清缓存，第一次启动没网络，重启一次后就正常了。
不用13的话，就用之前220629吧，没啥更新的。
