### ISSUE TITLE
XPS15-9570-OC-BRCM-221006版本后dw1830网卡无法正常驱动

### ISSUE THREAD

**Issue by fjsmzlx** [xxxzc/xps15-9570-macos#109]
更新XPS15-9570-OC-BRCM-221006版本后dw1830网卡无法正常驱动，XPS15-9570-OC-BRCM-220629这个版本正常。

**Comment by xxxzc** [comment]
也有人反馈不行，但我的是正常的，奇怪

**Comment by PPHAC** [comment]
这个版本我也遇到了1820a网卡无法驱动，而且开机后过一段时间，usb接口都断开连接，重新插入都没用，只能重启电脑。

**Comment by imguoguo** [comment]
更新[XPS15-9570-OC-BRCM-221006](https://github.com/xxxzc/xps15-9570-macos/releases/download/221005/XPS15-9570-OC-BRCM-221006.zip)版本后dw1560网卡在Monterey和Ventura也无法正常驱动，刚更新完系统后网卡可以使用，重启一次以后就无法正常使用了

**Comment by bjbo0ng** [comment]
Tested with Wifi card DW1560 + Ventura 13.2: not working with OC version "XPS15-9570-OC-BRCM-221006". Can i use OC "XPS15-9570-OC-BRCM-221006" with OS Monterey?

**Comment by fjsmzlx** [comment]
> 也有人反馈不行，但我的是正常的，奇怪

更新Monterey，XPS15-9570-OC-BRCM-221006版本dw1830网卡正常驱动，偶发异常，使用kext utility刷新缓存后重启恢复正常。

**Comment by fjsmzlx** [comment]
> 更新[XPS15-9570-OC-BRCM-221006](https://github.com/xxxzc/xps15-9570-macos/releases/download/221005/XPS15-9570-OC-BRCM-221006.zip)版本后dw1560网卡在Monterey和Ventura也无法正常驱动，刚更新完系统后网卡可以使用，重启一次以后就无法正常使用了

使用kext utility刷新缓存后重启恢复正常。

**Comment by xxxzc** [comment]
Sorry, I have deleted the macOS for a long time, you can try this [230209](https://github.com/xxxzc/xps15-9570-macos/releases/tag/230209) if you are still using my config.  @bjbo0ng @imguoguo @fjsmzlx

**Comment by fjsmzlx** [comment]
已解决，感谢感谢。
