### ISSUE TITLE
Sidecar not working

### ISSUE THREAD

**Issue by romancin** [xxxzc/xps15-9570-macos#11]
This is the last issue and the only real one I have found using your OpenCore configuration. After using your repo 1 entire week, I am amazed, your Power Management is the best of all the repos I tried, but right now I needed to change back to LuletterSoul's one with Clover, as sidecar is not working on it, and I don't have problems using it on LuletterSoul repo.

Do you know how it can be fixed?

Thank you very much!

**Comment by xxxzc** [comment]
Add following to DeviceProperties>Add>PciRoot(0x0)/Pci(0x2,0x0)
```
<key>device-id</key>
<data>
mz4AAA==
</data>
```
If not working, use this USBPorts.kext
[USBPorts.kext.zip](https://github.com/xxxzc/xps15-9570-macos/files/4143489/USBPorts.kext.zip)

If still not working, there's nothing I can do since I have no sidecar-supported device.

**Comment by romancin** [comment]
Tried both options and It is worse than before, iPad stops appearing in the AirPlay menu when applied this. Thank you anyways for your hard work!

For reference, my wifi card is DW1560.

**Comment by M69W** [comment]
> Tried both options and It is worse than before, iPad stops appearing in the AirPlay menu when applied this. Thank you anyways for your hard work!
> 
> For reference, my wifi card is DW1560.

if LuletterSoul's Clover is works,
try it

https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/blob/master/EFI/CLOVER/config.plist#L502-L510

**Comment by romancin** [comment]
Tried, but not working :(
