### ISSUE TITLE
[OC](https://github.com/xxxzc/xps15-9570-macos/releases/tag/200130) 使用反馈

### ISSUE THREAD

**Issue by M69W** [xxxzc/xps15-9570-macos#12]
机型：xps i5 8300h + 4k + DW1820A
系统：15.3
使用的[OC](https://github.com/xxxzc/xps15-9570-macos/releases/tag/200130)

- 开机第一阶段logo 太小【 `UIScale` 】：
https://github.com/xxxzc/xps15-9570-macos/blob/master/OC/config.plist#L527 这个值无效
改为`<data>Ag==</data>`

- config SIP 开机(估计自身情况需要)【 `csr-active-config` 】
https://github.com/xxxzc/xps15-9570-macos/blob/master/OC/config.plist#L537 这个值是开启
关闭改为：`5wMAAA==`

-  HDMI 音频输出失效
加回 `驱动`和`device-id`：
`FakePCIID.kext` 和 `FakePCIID_Intel_HDMI_Audio.kext`
`device-id`
https://github.com/xxxzc/xps15-9570-macos/commit/6b213c947a3b6e9a30be27525e61010ec119771d#diff-4fdeb792365bae2e6faf1a304f876e74L209-L212

以上数值已转码，
具体看参考：https://blog.daliansky.net/OpenCore-BootLoader.html

PS：`DA300`转HDMI 可能会出现内置屏幕黑屏现象，
解决：合盖开盖 或 无操作等一会儿屏幕睡眠后再唤醒，内置屏幕亮后就正常了

**Comment by adityahota** [comment]
Adding FakePCCID didn't work for me. Still no hot swap HDMI audio.

Could you detail your steps?

**Comment by M69W** [comment]
> Adding FakePCCID didn't work for me. Still no hot swap HDMI audio.
> 
> Could you detail your steps?

### Clover
```
<key>Devices</key>
<dict>
	<key>Properties</key>
	<dict>
		<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
		<dict>
			<key>device-id</key>
			<data>
			cKEAAA==
			</data>
			<key>layout-id</key>
			<integer>72</integer>
		</dict>
	</dict>
</dict>
```

### OC
```
<key>DeviceProperties</key>
<dict>
	<key>Add</key>
	<dict>
		<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
		<dict>
			<key>device-id</key>
			<data>
			cKEAAA==
			</data>
			<key>layout-id</key>
			<integer>72</integer>
		</dict>
	<dict>
<dict>
```

add `device-id` to your `config.plist` 
and put  `FakePCIID_Intel_HDMI_Audio.kext` 、`FakePCIID.kext` to your  `EFI/OC or Clover/Kexts`

[kexts.zip](https://github.com/xxxzc/xps15-9570-macos/files/4174000/kexts.zip) download from https://bitbucket.org/RehabMan/os-x-fake-pci-id/downloads/

**Comment by adityahota** [comment]
It worked! Thank you.

**Comment by carlosxfigueroa** [comment]
do I need to add this to get hdmi working?

**Comment by adityahota** [comment]
Only to get audio over HDMI port.

HDMI video (without audio) was already working.

**Comment by carlosxfigueroa** [comment]
with what smbios? hdmi doesnt work at all for me

**Comment by adityahota** [comment]
MacBookPro15,1

**Comment by carlosxfigueroa** [comment]
did you do anything special to get hdmi working? plugged in with different cables and nothing

**Comment by adityahota** [comment]
Are you using the config.plist from this repository? If so, I didn't have to make any changes--I did have to add in the kext information for FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext and the device information for the audio selector. Other than that, nothing else needed.

Do you have the 4K or 1080p screen?

**Comment by carlosxfigueroa** [comment]
im using the config from this repository, and i have 1080p, the onlt chnages i made were moving voodoo kext into system/library and disabling sip and the uichange

**Comment by M69W** [comment]
> im using the config from this repository, and i have 1080p, the onlt chnages i made were moving voodoo kext into system/library and disabling sip and the uichange

Oc or Clover?
Could you sent your `config.plist` to here?

**Comment by carlosxfigueroa** [comment]
im using OC, also sometimes audio goes out after a couple reboots then comes back next reboot have you guys experience this?
[config copy.plist.zip](https://github.com/xxxzc/xps15-9570-macos/files/4176448/config.copy.plist.zip)

**Comment by M69W** [comment]
> im using OC, also sometimes audio goes out after a couple reboots then comes back next reboot have you guys experience this?
> [config copy.plist.zip](https://github.com/xxxzc/xps15-9570-macos/files/4176448/config.copy.plist.zip)

your config.plist need to add `device-id`

<img width="767" alt="1" src="https://user-images.githubusercontent.com/15809201/74095943-1373e880-4b33-11ea-93cc-0425557f1403.png">
<img width="1272" alt="2" src="https://user-images.githubusercontent.com/15809201/74095945-1b338d00-4b33-11ea-99ea-e82925ef1f59.png">

**Comment by carlosxfigueroa** [comment]
it already has layout id 72

**Comment by M69W** [comment]
> it already has layout id 72

It seems to repeat but that is work for different devices
`layout-id` is for laptop.
`device-id` is for HDMI Audio ouput

**Comment by M69W** [comment]
> it already has layout id 72

https://github.com/RehabMan/OS-X-Fake-PCI-ID
have to inject "device-id"

**Comment by xxxzc** [comment]
已修改，感谢
