### ISSUE TITLE
音频注入信息要改一下，否则耳机爆音

### ISSUE THREAD

**Issue by OldDream** [xxxzc/xps15-9570-macos#14]
`
<key>PciRoot(0x0)/Pci(0x1f, 0x3)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>Built-in</string>
				<key>device_type</key>
				<string>Audio Controller</string>
				<key>layout-id</key>
				<integer>30</integer>
				<key>model</key>
				<string>Realtek ALC298</string>
			</dict>
`
在我这边得这样。。。

**Comment by xxxzc** [comment]
有用 Combojack 吗？

**Comment by OldDream** [comment]
> 有用 Combojack 吗？

有。。。用72的话外放正常，耳机爆音。不过9570似乎有若干个版本，有人用72是ok的。

**Comment by 0x10000** [comment]
我的也是ALC298，耳机声音特别小，注入id改为30后正常

**Comment by xxxzc** [comment]
已经换成了 16（和30差不多）
