### ISSUE TITLE
[FIX] UIScale not set to 2 properly

### ISSUE THREAD

**Issue by adityahota** [xxxzc/xps15-9570-macos#18]
In the provided config.plist, the UIScale value is not set properly. It should be set as a data value, not integer value.

The proposed fix (which worked for me) is as follows:
```
<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
			<dict>
				<key>UIScale</key>
				<data>Ag==</data>
			</dict>
```

@xxxzc

**Comment by xxxzc** [comment]
Thank you, dup. #12
