### ISSUE TITLE
关于TB3多屏输出

### ISSUE THREAD

**Issue by tofuliang** [xxxzc/xps15-9570-macos#19]
TB3插入TB16，通过TB16的HDMI（HKC T4000）和TB2(Dell U2414)连接显示器，其中 Dell U2414 会无显示输出。
从luletterSoul的配置中，把显示器注入部分扣回来就好了。
```
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
<dict>
	<key>AAPL,ig-platform-id</key>
	<data>
	AACbPg==
	</data>
	<key>disable-external-gpu</key>
	<data>
	AQAAAA==
	</data>
	<key>dpcd-max-link-rate</key>
	<data>
	FAAAAA==
	</data>
	<key>enable-dpcd-max-link-rate-fix</key>
	<data>
	AQAAAA==
	</data>
	<key>enable-hdmi-dividers-fix</key>
	<data>
	AQAAAA==
	</data>
	<key>enable-hdmi20</key>
	<data>
	AQAAAA==
	</data>
	<key>enable-lspcon-support</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-con1-alldata</key>
	<data>
	AQUJAAAEAACHAQAA
	</data>
	<key>framebuffer-con1-enable</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-con2-alldata</key>
	<data>
	AgYJAAAEAACHAQAA
	</data>
	<key>framebuffer-con2-enable</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-con2-has-lspcon</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-con2-preferred-lspcon-mode</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-con3-alldata</key>
	<data>
	AwQKAAAIAACHAQAA
	</data>
	<key>framebuffer-con3-enable</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-patch-enable</key>
	<data>
	AQAAAA==
	</data>
	<key>framebuffer-portcount</key>
	<data>
	BAAAAA==
	</data>
	<key>framebuffer-unifiedmem</key>
	<data>
	AAAAgA==
	</data>
</dict>
```

另外，TB3的热插拔，[这个文章](https://github.com/osy86/HaC-Mini/blob/master/details/thunderbolt-3-fix.md)有帮助么，搞不懂DSDT，感觉无从下手啊。
[macOS-IOElectrify](https://github.com/the-darkvoid/macOS-IOElectrify) 试了一下，好像没啥用

**Comment by xxxzc** [comment]
感谢，我还以为 con1 和 con2 已经定义正确了，只要另外加上 con3 就好。 [bavariancake](https://github.com/bavariancake/XPS9570-macOS#enabling-external-display-support) 的描述应该是正确的，lspcon 确定是加在 con2 上而不是 con3 上吗？

---

那个文章我看过，没有找到 NUC 的 DSDT，另外他库里关于雷电的SSDT比文章描述多了好多的内容，无法确定哪些是原来 NUC 或者 MAC 带的，哪些是他额外增加的，完全看不下去，最近也没空研究。macOS-IOElectrify 应该是用于启动时强制启动雷电，并不能解决热插拔和睡眠的问题。

**Comment by tofuliang** [comment]
> lspcon 确定是加在 con2 上而不是 con3 上吗？


这个我不知道如何验证，只是简单把luletterSoul那个拿了过来而已，应该如何验证呢？貌似我的设备不支持HDMI2.0😅

另外一个小问题，我长期连着TB16外接双屏，合盖当台式机使用(冷启动也是合盖)，C面中间的指示灯会 2黄7白 这样的闪，查了下 说是屏幕错误？
还有就是用的网卡用的1560，经常睡眠唤醒就会丢失蓝牙连接，必须关掉蓝牙再重新开启，才能连上蓝牙设备，你的有这样的问题么？

**Comment by xxxzc** [comment]
这个不太重要，现在我想确定下，如果用雷电口连两个外置显示器，连上了哪几个 connectors，
麻烦用 hackintool 看下 Patch-Connectors 连了哪几个：
<img width="692" alt="Screen Shot 2020-02-24 at 11 15 13 PM" src="https://user-images.githubusercontent.com/22726929/75164267-86987400-575b-11ea-957e-b49abc9292de.png">

---

> 另外一个小问题，我长期连着TB16外接双屏，合盖当台式机使用(冷启动也是合盖)，C面中间的指示灯会 2黄7白 这样的闪，查了下 说是屏幕错误？

这个不太懂，Windows下这样使用会闪吗？不影响使用就忽视吧

---
我的蓝牙完全用不了= =睡眠后掉蓝牙很正常，目前似乎无解

**Comment by tofuliang** [comment]
> 这个不太重要，现在我想确定下，如果用雷电口连两个外置显示器，连上了哪几个 connectors，
> 麻烦用 hackintool 看下 Patch-Connectors 连了哪几个：


仔细看了下，我的连接方式是

TB16<->大DP<->大DP<->HKC T4000
TB16<->miniDP<->HDMI<->U2414

连接的是1，2两个
TB16上还有一个HDMI接口，但是我显示器都上在支架上，没拉过来试了，如果有需要的话，我再试试吧。

至于TB16上的VGA，应该是TB16的芯片转换出来的信号，试过画质跟数字信号有明显差距，就不用测试了吧。

![image](https://user-images.githubusercontent.com/1814685/75166768-5f43a600-575f-11ea-83e9-fb85088c73d2.png)
