### ISSUE TITLE
刚安装好，挺好用的，目前1080 使用的oc版本，字体发虚的严重

### ISSUE THREAD

**Issue by EmiCham** [xxxzc/xps15-9570-macos#2]
这个问题怎么解决啊。我用的1820a。我发现几乎啥都不做，就可以上网了。真神奇。目前就一个很不爽的问题1080的屏幕，字体有点虚。

**Comment by xxxzc** [comment]
1820a 能用是因为这个：
```
<key>PciRoot(0x0)/Pci(0x1c,0x0)/Pci(0x0,0x0)</key>
<dict>
        <key>pci-aspm-default</key>
        <integer>0</integer>
</dict>
```

参考 [THE Solution:Dell DW1820A](https://www.tonymacx86.com/threads/the-solution-dell-dw1820a-broadcom-bcm94350zae-macos-15.288026/) 和 https://github.com/daliansky/daliansky.github.io/issues/200
