### ISSUE TITLE
15.3 + OC 插着电源似乎无法睡眠？

### ISSUE THREAD

**Issue by M69W** [xxxzc/xps15-9570-macos#20]
机型：XPS 9570 i5-8300H + 4K
系统：10.15.3 (19D76)
使用 [OC版本](https://github.com/xxxzc/xps15-9570-macos/releases/tag/200219-1)

### 节能：
电源适配器(显示3项)

✖️当显示器关闭时，防止电脑自动进入睡眠
☑️ 如果可能，使硬盘进入睡眠
✖️接上电源适配器是启动电能小憩

#### 异常情况：
`插着电源无法睡眠`？秒醒

#### 正常情况：
左上角菜单：睡眠，或 Fn + Insert 睡眠则正常

### 更新说明
只要插上[type-C转USB3.0](https://item.jd.com/2184573.html) ，过一阵子风扇就明显响动，拔掉则恢复安静，尝试不下3次

插入前：
<img width="1920" alt="插入前" src="https://user-images.githubusercontent.com/15809201/75598633-25b0c900-5ad8-11ea-9d36-025610f4dd06.png">
插入后：
<img width="1920" alt="插入后" src="https://user-images.githubusercontent.com/15809201/75598643-32cdb800-5ad8-11ea-995e-4b6c09c7d7c6.png">

```
➜  ~ log show --last 1d | grep "Wake reason"
2020-02-28 01:01:28.974800+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
2020-02-28 01:01:28.974802+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
2020-02-28 09:28:37.066199+0800 0x1687b    Default     0x0                  102    0    powerd: [powerd:sleepWake] Wake reason: "<private>"  identity: "<private>"
2020-02-28 09:29:02.904133+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
2020-02-28 09:29:02.904135+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
```

请问该如何测试或修复？

**Comment by xxxzc** [comment]
秒醒问题可以把SSDT-GPRW和GPRW重命名加回来试试，我和一个朋友测试没这个问题就删了，有可能是我们都是使用typec充电？

> 只要插上type-C转USB3.0 ，过一阵子风扇就明显响动

这个不懂= =

**Comment by M69W** [comment]
具体是
（空运行软件下）
接上type-c 转接头，两三分钟开始出现风扇响声（能感觉到明显的风扇响声）
拔掉，大概三分钟后，风扇响声就没了(感觉不到了)

USB接口接外接设备，没有这个现象

是否跟上面显示雷电设备（一楼截图）有关？

**Comment by M69W** [comment]
继续跟踪：
昨晚拔了type-c转换头：今早发现可以睡眠
不知道是否这个type-c转换头 导致睡眠问题？

**Comment by xxxzc** [comment]
跟显示雷电设备无关，9570 c口的USB3控制器就是挂在雷电（RP17.PXSX）上。

这转接头啥都没接也会造成风扇转么？

睡眠问题可以用 `pmset -g log` 看

**Comment by M69W** [comment]
上面那个type+C，DA300 都会出现这个现象
下面是开机后没有睡眠过直接提取的

[sm.log](https://github.com/xxxzc/xps15-9570-macos/files/4281268/sm.log)

**Comment by tiger511** [comment]
> 机型：XPS 9570 i5-8300H + 4K
> 系统：10.15.3 (19D76)
> 使用 [OC版本](https://github.com/xxxzc/xps15-9570-macos/releases/tag/200219-1)
> 
> ### 节能：
> 电源适配器(显示3项)
> 
> ✖️当显示器关闭时，防止电脑自动进入睡眠
> ☑️ 如果可能，使硬盘进入睡眠
> ✖️接上电源适配器是启动电能小憩
> 
> ### 问题描述：
> #### 异常情况：
> `插着电源无法睡眠`？秒醒
> 
> #### 正常情况：
> 左上角菜单：睡眠，或 Fn + Insert 睡眠则正常
> 
> ### 更新说明
> 只要插上[type-C转USB3.0](https://item.jd.com/2184573.html) ，过一阵子风扇就明显响动，拔掉则恢复安静，尝试不下3次
> 
> 插入前：
> <img alt="插入前" width="1920" src="https://user-images.githubusercontent.com/15809201/75598633-25b0c900-5ad8-11ea-9d36-025610f4dd06.png">
> 插入后：
> <img alt="插入后" width="1920" src="https://user-images.githubusercontent.com/15809201/75598643-32cdb800-5ad8-11ea-995e-4b6c09c7d7c6.png">
> 
> ```
> ➜  ~ log show --last 1d | grep "Wake reason"
> 2020-02-28 01:01:28.974800+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
> 2020-02-28 01:01:28.974802+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
> 2020-02-28 09:28:37.066199+0800 0x1687b    Default     0x0                  102    0    powerd: [powerd:sleepWake] Wake reason: "<private>"  identity: "<private>"
> 2020-02-28 09:29:02.904133+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
> 2020-02-28 09:29:02.904135+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
> ```
> 
> 请问该如何测试或修复？

How did you get it working with Samsung SM981 SSD? I just get restart when installing.

**Comment by M69W** [comment]
> Samsung

it's Samsung 970 evo

**Comment by M69W** [comment]
> > 机型：XPS 9570 i5-8300H + 4K
> > 系统：10.15.3 (19D76)
> > 使用 [OC版本](https://github.com/xxxzc/xps15-9570-macos/releases/tag/200219-1)
> > ### 节能：
> > 电源适配器(显示3项)
> > ✖️当显示器关闭时，防止电脑自动进入睡眠
> > ☑️ 如果可能，使硬盘进入睡眠
> > ✖️接上电源适配器是启动电能小憩
> > ### 问题描述：
> > #### 异常情况：
> > `插着电源无法睡眠`？秒醒
> > #### 正常情况：
> > 左上角菜单：睡眠，或 Fn + Insert 睡眠则正常
> > ### 更新说明
> > 只要插上[type-C转USB3.0](https://item.jd.com/2184573.html) ，过一阵子风扇就明显响动，拔掉则恢复安静，尝试不下3次
> > 插入前：
> > <img alt="插入前" width="1920" src="https://user-images.githubusercontent.com/15809201/75598633-25b0c900-5ad8-11ea-9d36-025610f4dd06.png">
> > 插入后：
> > <img alt="插入后" width="1920" src="https://user-images.githubusercontent.com/15809201/75598643-32cdb800-5ad8-11ea-995e-4b6c09c7d7c6.png">
> > ```
> > ➜  ~ log show --last 1d | grep "Wake reason"
> > 2020-02-28 01:01:28.974800+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
> > 2020-02-28 01:01:28.974802+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
> > 2020-02-28 09:28:37.066199+0800 0x1687b    Default     0x0                  102    0    powerd: [powerd:sleepWake] Wake reason: "<private>"  identity: "<private>"
> > 2020-02-28 09:29:02.904133+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
> > 2020-02-28 09:29:02.904135+0800 0x74       Default     0x0                  0      0    kernel: (AppleACPIPlatform) AppleACPIPlatformPower Wake reason: PBTN (User)
> > ```
> > 
> > 
> > 请问该如何测试或修复？
> 
> How did you get it working with Samsung SM981 SSD? I just get restart when installing.

it's Samsung 970 evo.

**Comment by tiger511** [comment]
> it's Samsung 970 evo.

In your screenshot it says PM981 ,i thought you managed to get it working in stock samsung SSD 🤣
