### ISSUE TITLE
oc 0.5.6 配置有误

### ISSUE THREAD

**Issue by ATFieldBeast** [xxxzc/xps15-9570-macos#22]
看oc作者的[sample](https://github.com/acidanthera/OpenCorePkg/blob/d9f23b27363d8d53c7e6079bb70b2b8963d8fc84/Docs/Sample.plist#L582-L604)和文档得知，Boot[这里](https://github.com/xxxzc/xps15-9570-macos/blob/19bceb962165af378ec5b358c12e7e604d437923/OC/config.plist#L490-L500)的UsePicker已经弃用改成PickerMode了，仍然使用UsePicker的话开机会闪过一行如下警告
![IMG_5026](https://user-images.githubusercontent.com/22592396/75986092-5d7c9e00-5f28-11ea-84dd-e6ed9a517672.png)

**Comment by xxxzc** [comment]
感谢，忘记删了
