### ISSUE TITLE
用了oc引导双系统后 win下雷电3外接显卡没有反应

### ISSUE THREAD

**Issue by 82Ice** [xxxzc/xps15-9570-macos#24]
开机提示thunderbolt pcie device enumeration mode has switch to native并一闪而过。请问有什么解决方案 吗

**Comment by 82Ice** [comment]
啊。解决了。在bios里关闭auto swticj就行了

**Comment by JackyWWX** [comment]
> 开机提示thunderbolt pcie device enumeration mode has switch to native并一闪而过。请问有什么解决方案 吗

进bios，雷电3设置为 BIOS assist enumeration
详见：[https://github.com/bavariancake/XPS9570-macOS](url)

**Comment by 82Ice** [comment]
好的。谢谢
