### ISSUE TITLE
Type-C读卡器是不能使用？

### ISSUE THREAD

**Issue by JackyWWX** [xxxzc/xps15-9570-macos#25]
7590 1080p屏幕刚从clover转来OC，clover下type-c读卡器不能使用，oc也一样么？
另，不知9570的触摸板是否同样情况：
1、不用TPDX，kernel_task占用一直14%，使用不够顺滑，有滞后感，而且不能使用双击拖移
2、用屏蔽触摸屏的TPDX，kernel_task便是同描述一样，但使用很顺滑，滞后感较低，可以使用双击拖移，和我在clover下体验一致
HDMI和clover下一样无法热插拔，可通过睡眠解决
clover下若核显高负载后长时间睡眠，睡醒后极大几率保持300MHz，在tonymacx86上看过UHD630同样问题。OC后测试几次短暂睡眠暂无发现

**Comment by JackyWWX** [comment]
Type-C不能热插拔，必须开机前插上才可识别，开机后不能插拔。Type-C速度只有2.0，远景一老哥给了定制usbport，恢复正常速度

**Comment by geek5nan** [comment]
> Type-C不能热插拔，必须开机前插上才可识别，开机后不能插拔。Type-C速度只有2.0，远景一老哥给了定制usbport，恢复正常速度

Type-C 速度不匹配这个问题，我猜测是 XPS 9750 与 XPS 7590 的 USB 布局不太一样导致的。
作者的 USBPort.kext 可能适用于 XPS 9750 的 USB 布局，而我发给你的 USBPort.kext 则是为 XPS 7590 定制的，所以更适合你的设备。

热插拔的问题，非雷电协议的 Type-C 设备也不能热插拔吗？

**Comment by WildBeastRouen** [comment]
XPS 7590 把SSDT-TbtTypeC的XHC重命名成XHC2可以解决TypeC热插拔和速度问题

**Comment by JackyWWX** [comment]
> XPS 7590 把SSDT-TbtTypeC的XHC重命名成XHC2可以解决TypeC热插拔和速度问题

OK，尝试下

**Comment by JackyWWX** [comment]
> XPS 7590 把SSDT-TbtTypeC的XHC重命名成XHC2可以解决TypeC热插拔和速度问题
找到两个补丁，是这个么，逐一尝试不行
`<key>Comment</key>
					<string>change XHC to XHC2 on TBDU</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					WEhDXwhfQURSAA==
					</data>
					<key>Replace</key>
					<data>
					WEhDMghfQURSAA==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>change TBDU.XHC to TBDU.XHC2</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					VEJEVVhIQ18=
					</data>
					<key>Replace</key>
					<data>
					VEJEVVhIQzI=
					</data>
				</dict>`

**Comment by JackyWWX** [comment]
> <key>Comment</key>
					<string>change XHC to XHC2 on TBDU</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					WEhDXwhfQURSAA==
					</data>
					<key>Replace</key>
					<data>
					WEhDMghfQURSAA==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>change TBDU.XHC to TBDU.XHC2</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					VEJEVVhIQ18=
					</data>
					<key>Replace</key>
					<data>
					VEJEVVhIQzI=
					</data>
				</dict>

> > Type-C不能热插拔，必须开机前插上才可识别，开机后不能插拔。Type-C速度只有2.0，远景一老哥给了定制usbport，恢复正常速度
> 
> Type-C 速度不匹配这个问题，我猜测是 XPS 9750 与 XPS 7590 的 USB 布局不太一样导致的。
> 作者的 USBPort.kext 可能适用于 XPS 9750 的 USB 布局，而我发给你的 USBPort.kext 则是为 XPS 7590 定制的，所以更适合你的设备。
> 
> 热插拔的问题，非雷电协议的 Type-C 设备也不能热插拔吗？

不行，我只是普通读卡器

**Comment by WildBeastRouen** [comment]
> > Comment
> > change XHC to XHC2 on TBDU
> > Disabled
> > 
> > Find
> > 
> > WEhDXwhfQURSAA==
> > 
> > Replace
> > 
> > WEhDMghfQURSAA==
> > 
> > 
> > 
> > Comment
> > change TBDU.XHC to TBDU.XHC2
> > Disabled
> > 
> > Find
> > 
> > VEJEVVhIQ18=
> > 
> > Replace
> > 
> > VEJEVVhIQzI=
> 
> > > Type-C不能热插拔，必须开机前插上才可识别，开机后不能插拔。Type-C速度只有2.0，远景一老哥给了定制usbport，恢复正常速度
> > 
> > 
> > Type-C 速度不匹配这个问题，我猜测是 XPS 9750 与 XPS 7590 的 USB 布局不太一样导致的。
> > 作者的 USBPort.kext 可能适用于 XPS 9750 的 USB 布局，而我发给你的 USBPort.kext 则是为 XPS 7590 定制的，所以更适合你的设备。
> > 热插拔的问题，非雷电协议的 Type-C 设备也不能热插拔吗？
> 
> 不行，我只是普通读卡器

直接套别人的重命名补丁是行不通的，父设备名称不同，而且需要的是对指定SSDT重命名而非全局重命名，必须自己找出SSDT的设备名称16进制值，再转换成base64

			<dict>
				<key>Comment</key>
				<string>Rename XHC_ to XHC2 in TbtTypeC</string>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>gkkgWEhDXwg=</data>
				<key>OemTableId</key>
				<data>VGJ0VHlwZUM=</data>
				<key>Replace</key>
				<data>gkkgWEhDMgg=</data>
				<key>TableSignature</key>
				<data>U1NEVA==</data>
			</dict>

**Comment by JackyWWX** [comment]
> > > Comment
> > > change XHC to XHC2 on TBDU
> > > Disabled
> > > Find
> > > WEhDXwhfQURSAA==
> > > Replace
> > > WEhDMghfQURSAA==
> > > Comment
> > > change TBDU.XHC to TBDU.XHC2
> > > Disabled
> > > Find
> > > VEJEVVhIQ18=
> > > Replace
> > > VEJEVVhIQzI=
> > 
> > 
> > > > Type-C不能热插拔，必须开机前插上才可识别，开机后不能插拔。Type-C速度只有2.0，远景一老哥给了定制usbport，恢复正常速度
> > > 
> > > 
> > > Type-C 速度不匹配这个问题，我猜测是 XPS 9750 与 XPS 7590 的 USB 布局不太一样导致的。
> > > 作者的 USBPort.kext 可能适用于 XPS 9750 的 USB 布局，而我发给你的 USBPort.kext 则是为 XPS 7590 定制的，所以更适合你的设备。
> > > 热插拔的问题，非雷电协议的 Type-C 设备也不能热插拔吗？
> > 
> > 
> > 不行，我只是普通读卡器
> 
> 直接套别人的重命名补丁是行不通的，父设备名称不同，而且需要的是对指定SSDT重命名而非全局重命名，必须自己找出SSDT的设备名称16进制值，再转换成base64
> 
> ```
> 		<dict>
> 			<key>Comment</key>
> 			<string>Rename XHC_ to XHC2 in TbtTypeC</string>
> 			<key>Enabled</key>
> 			<true/>
> 			<key>Find</key>
> 			<data>gkkgWEhDXwg=</data>
> 			<key>OemTableId</key>
> 			<data>VGJ0VHlwZUM=</data>
> 			<key>Replace</key>
> 			<data>gkkgWEhDMgg=</data>
> 			<key>TableSignature</key>
> 			<data>U1NEVA==</data>
> 		</dict>
> ```

感谢，这点操作我还不会，只会搜索找现成，哈哈

**Comment by JackyWWX** [comment]
> > > Comment
> > > change XHC to XHC2 on TBDU
> > > Disabled
> > > Find
> > > WEhDXwhfQURSAA==
> > > Replace
> > > WEhDMghfQURSAA==
> > > Comment
> > > change TBDU.XHC to TBDU.XHC2
> > > Disabled
> > > Find
> > > VEJEVVhIQ18=
> > > Replace
> > > VEJEVVhIQzI=
> > 
> > 
> > > > Type-C不能热插拔，必须开机前插上才可识别，开机后不能插拔。Type-C速度只有2.0，远景一老哥给了定制usbport，恢复正常速度
> > > 
> > > 
> > > Type-C 速度不匹配这个问题，我猜测是 XPS 9750 与 XPS 7590 的 USB 布局不太一样导致的。
> > > 作者的 USBPort.kext 可能适用于 XPS 9750 的 USB 布局，而我发给你的 USBPort.kext 则是为 XPS 7590 定制的，所以更适合你的设备。
> > > 热插拔的问题，非雷电协议的 Type-C 设备也不能热插拔吗？
> > 
> > 
> > 不行，我只是普通读卡器
> 
> 直接套别人的重命名补丁是行不通的，父设备名称不同，而且需要的是对指定SSDT重命名而非全局重命名，必须自己找出SSDT的设备名称16进制值，再转换成base64
> 
> ```
> 		<dict>
> 			<key>Comment</key>
> 			<string>Rename XHC_ to XHC2 in TbtTypeC</string>
> 			<key>Enabled</key>
> 			<true/>
> 			<key>Find</key>
> 			<data>gkkgWEhDXwg=</data>
> 			<key>OemTableId</key>
> 			<data>VGJ0VHlwZUM=</data>
> 			<key>Replace</key>
> 			<data>gkkgWEhDMgg=</data>
> 			<key>TableSignature</key>
> 			<data>U1NEVA==</data>
> 		</dict>
> ```

添加后重启仍无效，估计真的是我雷电3 bios设置问题，hackintool USB中看不到，我记得之前在win下貌似也没看到，要在win折腾下先

**Comment by JackyWWX** [comment]
果然，是我雷电3的问题，win下更新雷电3固件后，就正常识别可热插拔

**Comment by geek5nan** [comment]
> 果然，是我雷电3的问题，win下更新雷电3固件后，就正常识别可热插拔

你修复 C 口热插拔的时候，除了更新固件，还做其他调整了吗

**Comment by JackyWWX** [comment]
> > 果然，是我雷电3的问题，win下更新雷电3固件后，就正常识别可热插拔
> 
> 你修复 C 口热插拔的时候，除了更新固件，还做其他调整了吗

还有添加xhc to xhc2补丁

**Comment by geek5nan** [comment]
1. 定制 USBPort.kext 解决 C 口速率问题
2. 更新固件并添加 Rename XHC to XHC2 补丁，解决热插拔问题

**Comment by JackyWWX** [comment]
> 1. 定制 USBPort.kext 解决 C 口速率问题
> 2. 更新固件并添加 Rename XHC to XHC2 补丁，解决热插拔问题

对，还有雷电3 bios具体设置为BIOS assist enumeration，安全性我直接设成“no securety”。
系统PCI列表下出现2个ExpressCard，估计一个雷电，一个Type-C
你也是这样么？

**Comment by WildBeastRouen** [comment]
> > 1. 定制 USBPort.kext 解决 C 口速率问题
> > 2. 更新固件并添加 Rename XHC to XHC2 补丁，解决热插拔问题
> 
> 对，还有雷电3 bios具体设置为BIOS assist enumeration，安全性我直接设成“no securety”。
> 系统PCI列表下出现2个ExpressCard，估计一个雷电，一个Type-C
> 你也是这样么？

XPS 7590不需要SSDT-TYPC和对应的重命名，这个热插拔补丁在7590没法和9570一样正常使用，右上角的ExpressCard图标只要点击退出就会kp，可以直接删除

**Comment by geek5nan** [comment]
你们的 ExpressCard 点击时也会重启吗？ 
PS： 我本还以为是我外置 MacOS 硬盘导致的

**Comment by JackyWWX** [comment]
ExpressCard我点击了不会重启，菜单栏的图标已删除

**Comment by JackyWWX** [comment]
> > > 1. 定制 USBPort.kext 解决 C 口速率问题
> > > 2. 更新固件并添加 Rename XHC to XHC2 补丁，解决热插拔问题
> > 
> > 
> > 对，还有雷电3 bios具体设置为BIOS assist enumeration，安全性我直接设成“no securety”。
> > 系统PCI列表下出现2个ExpressCard，估计一个雷电，一个Type-C
> > 你也是这样么？
> 
> XPS 7590不需要SSDT-TYPC和对应的重命名，这个热插拔补丁在7590没法和9570一样正常使用，右上角的ExpressCard图标只要点击退出就会kp，可以直接删除

说得我有点蒙了，用了9570的ssdt-Typec，以及你提供的重命名补丁，我自己在win下升级雷电3固件后，以及雷电3的相关bios设置。目前，7590 typr-c热插拔一切正常，外接拓展显示器及PD充电也正常

**Comment by JackyWWX** [comment]
今天下午用FCPX和AE Type-C外接屏做了会视频，睡眠回到家刚唤醒又出现GPU 300MHz的问题。问下两位大佬，有解么？tonymacx86能搜到同样问题，但不同型号非XPS，但都是UHD 630才出现

**Comment by geek5nan** [comment]
> XPS 7590不需要SSDT-TYPC和对应的重命名，这个热插拔补丁在7590没法和9570一样正常使用，右上角的ExpressCard图标只要点击退出就会kp，可以直接删除

在 XPS 7590 中使用 SSDT-TYPC 做了个测试，结果如下：

1. 使用 SSDT-TYPC ，状态栏显示 ExpressCard 图标，点击图标中的关闭选项时，电脑重启（可能是KP 导致 ）
2. 移除 SSDT-TYPC，状态栏不再显示 ExpressCard 图标。 
3. 无论是否使用 SSDT-TYPC ，通过 C 口外接 10Gb/s 硬盘时，热插拔均表现正常。

手边没有设备来测试 TYPE-C 显示器，不确定 SSDT-TYPC 对 TYPE-C 显示器是否有效。

小结：

1. SSDT-TYPC 的存在与否，对外置硬盘的热插拔均无影响。
2. SSDT-TYPC 对 TYPE-C 外接显示器的影响，有待验证。

**Comment by geek5nan** [comment]
> 今天下午用FCPX和AE Type-C外接屏做了会视频，睡眠回到家刚唤醒又出现GPU 300MHz的问题。问下两位大佬，有解么？tonymacx86能搜到同样问题，但不同型号非XPS，但都是UHD 630才出现

没有遇到这个问题，GPU 300MHz 截图发来看下。

**Comment by JackyWWX** [comment]
> > 今天下午用FCPX和AE Type-C外接屏做了会视频，睡眠回到家刚唤醒又出现GPU 300MHz的问题。问下两位大佬，有解么？tonymacx86能搜到同样问题，但不同型号非XPS，但都是UHD 630才出现
> 
> 没有遇到这个问题，GPU 300MHz 截图发来看下。

[https://www.tonymacx86.com/threads/uhd630-wake-issue-lowest-freq-locked-to-350mhz-cant-sleep-again.292086/](url)
和这个描述一致，里面评论也有7590，我用istat menu查看，最低锁在349MHz

**Comment by geek5nan** [comment]
<img width="400" alt="IPG" src="https://user-images.githubusercontent.com/3816374/77158640-b0388700-6ade-11ea-8b9f-5407c0d9ab19.png">

在我的 OLED 7590 上没有发现这个问题，不太清楚是什么原因导致的。

**Comment by JackyWWX** [comment]
用了一段时间，没出现问题，剪视频又会，最后发现如果fcpx或者ae正在后台渲染视频，这个时候盒盖睡眠，开盖GPU基本就会锁349MHz。
另外一个问题，继上次Win下更新雷电3驱动，macos下hackintool能看到雷电3驱动，type-c也能热插拔。但是，我用倍思的type-c转hdmi和pd充电拓展器后，重启雷电3失效，type-c也不能热插拔。无论clover或者oc，冷启动后，首次用这个type-c转hdmi拓展器，必定内屏黑屏卡住。如果冷启动后，进行一次盒盖睡眠后，就能正常使用。

**Comment by adityahota** [comment]
Does this enable USB 3.0 speeds via the USB C port on the 9570?
