### ISSUE TITLE
Thank you for your work! (not an issue)

### ISSUE THREAD

**Issue by jaromeyer** [xxxzc/xps15-9570-macos#26]
First this is not an issue at all! @xxxzc thank you very much for creating this repository. Now we finally have an alternative to clover for the XPS 9570. I was trying to get OC working few weeks ago but gave up hoping some smarter guys as you would create a working OC setup. And I appreciate that you decided to try to keep the whole repo in English even though it's not your main language. Even with a translator, I'm having a hard time understanding the other repos and issues documented in Chinese.

Btw what's the reason you are using VBoxHfs over HfsPlus? And what exactly isn't working with Bluetooth? I'd gladly have a look if you could point me in the right direction.

**Comment by xxxzc** [comment]
> what's the reason you are using VBoxHfs over HfsPlus?

Because [https://github.com/acidanthera/AppleSupportPkg](AppleSupportPkg) contains it.

> what exactly isn't working with Bluetooth

My situation:
1. My DW1830 has one antenna base broken, bluetooth is not working at all, e.g. galaxy buds connection drops soon after connecting
2. My DW1820a can work sometimes and will broke after sleeping

I can't guarantee that bluetooth works because:
1. I use DW1830 currently for better wifi compatibility so I can't test bluetooth with newly firmware/kext
2. There are many kinds of bluetooth devices
3. 9570 users use/switch to different wifi/bluetooth cards

**Comment by M69W** [comment]
Use DW1820A is better on [stable version drivers](http://7.daliansky.net/DW1820A/BT_for_DW1820A_Ver.2.zip)

By the way about the `Sidecar`:
Someone `remove the code` to make the Sidecar works on DW1820A :
```
<dict>
	<key>Devices</key>
	<dict>
		<key>Properties</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1c,0x0)/Pci(0x0)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>WLAN</string>
				<key>compatible</key>
				<string>pci14e4,4331</string>
				<key>device_type</key>
				<string>Airport Extreme</string>
				<key>model</key>
				<string>DW1820A (BCM4350) 802.11ac Wireless</string>
				<key>name</key>
				<string>Airport</string>
				<key>pci-aspm-default</key>
				<integer>0</integer>
			</dict>
		</dict>
	</dict>
</dict>
</plist>
```


@[tutorial](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)

**Comment by jaromeyer** [comment]
I'm currently using the DW1820a and its pretty stable at least Wi-Fi. The only thing I'm doing is disabling aspm. @M69W are you sure the other properties change something? Because as far as I know everything besides ```pci-aspm-default``` and ```compatible``` is cosmetic only. And regarding Bluetooth I'm pretty sure the drivers you have linked don't work on Catalina. You should use ```BrcmPatchRAM3.kext``` not ```BrcmPatchRAM2.kext``` according to the official repository.

Btw do you know if disabling aspm does the same as taping those 5pins? Because on Mojave without disabling aspm I had to do the tape mod on my DW1820a to even get it to boot and now on Catalina without aspm its running fine without the tape mod.

Last question has anyone tried disabling aspm on the DW1830 or DW1560? Because if they still work you could include that in the default ```config.plist``` to make all 3 card work out-of-the-box.

**Comment by xxxzc** [comment]
@jaromeyer that `BrcmPatchRAM2.kext` is a special version built for DW1820a that can work on Catalina.

> Last question has anyone tried disabling aspm on the DW1830 or DW1560? Because if they still work you could include that in the default config.plist to make all 3 card work out-of-the-box.

disabling aspm on the DW1830 will make wifi broken after sleeping in my test

**Comment by jaromeyer** [comment]
oh didn't know that there was a special version for catalina. thanks guys. gonna try if its any better than version 3.

**Comment by romancin** [comment]
> tutorial

Do you know what is needed to change for another WiFi cards? Thank you!

**Comment by jaromeyer** [comment]
Bluetooth on the DW1820a works fine with Daliansky's kexts. Even after a full night of sleep it automatically connects to my magic mouse after about one minute. Thanks, @M69W!
@romancin what exactly do you mean? You will need a compatible card like the DW1820a, a Torx t5 screwdriver for the bottom and a Phillips head screwdriver for the two screws behind the flap cover and for removing the card

**Comment by sarkrui** [comment]
Folks, just get a BCM94360CD or BCM94360CS2 with an M.2  A+E adapter and you're free. Sidecar, Import from iOS mobiles, AirDrop, Handoff, no problem!
 @jaromeyer @romancin he was probably asking about what needs to change on DW1560.

**Comment by jaromeyer** [comment]
Yeah thats another option but i dont use any of those apple features so im perfectly fine with the dw1820a. and imo extending the slot and both antennas is a bit of a hack and not really a clean solution, but if you need any of those feature its nice that there is a working option.

**Comment by M69W** [comment]
> Folks, just get a BCM94360CD or BCM94360CS2 with an M.2 A+E adapter and you're free. Sidecar, Import from iOS mobiles, AirDrop, Handoff, no problem!
> @jaromeyer @romancin he was probably asking about what needs to change on DW1560.

Aother Choose is BCM943602CS with an M.2 A+E adapter if your laptop have three antennas

**Comment by romancin** [comment]
> Bluetooth on the DW1820a works fine with Daliansky's kexts. Even after a full night of sleep it automatically connects to my magic mouse after about one minute. Thanks, @M69W!
> @romancin what exactly do you mean? You will need a compatible card like the DW1820a, a Torx t5 screwdriver for the bottom and a Phillips head screwdriver for the two screws behind the flap cover and for removing the card

Yeah, that's right, that was what I was asking. FYI, sidecar on DW1560 started working perfect on 10.15.4 :)
