### ISSUE TITLE
Full range of brightness is not available

### ISSUE THREAD

**Issue by tiger511** [xxxzc/xps15-9570-macos#27]
With your config, highest brightness equals nearly 50%-60% brightness of Windows.I think brightness config should be tuned up.My panel is Sharp 4K panel that is different from XPS 9550 4k Panel. I have both laptops.This problem exists in 9550 Panel too with your 9550 config,i dont know if you noticed it or not.

One more problem,The brightness keys have very minimal impact in lower steps and very high impact in the last 3 steps.I tried to fix it with " Name (SCFT, 45)" in SSDT-BCKM.aml  but it doesn't have any effect.Can you explain how do we distribute brightness adjustments more equally.

**Comment by xxxzc** [comment]
I knew.

Brightness control levels are returned by _BCL method:

```
            Method (_BCL, 0, Serialized)  // _BCL: Brightness Control Levels
            {
                If ((OIDE () >= One))
                {
                    Return (Package (0x67)
                    {
                        0x50, 
                        0x32, 
                        ... // following is level value
                    })
                }
                Else
                {
                    Name (BRT1, Buffer (0x0D){})
                    CreateByteField (BRT1, Zero, BRT2)
                    BRT2 = One
                    Local2 = GENS (0x09, BRT1, SizeOf (BRT1))
                    Local0 = Zero
                    Local1 = 0x0D
                    While ((Local0 < Local1))
                    {
                        Local3 = BBRD (Local2, Local0)
                        DBCL [Local0] = Local3
                        Local0++
                    }

                    Return (DBCL) /* \_SB_.PCI0.GFX0.LCD_.DBCL */
                }
            }
```

You can try to patch this method to distribute brightness levels more equally. 

I'm very busy recently, I won't be free until the end of April.

**Comment by tiger511** [comment]
Where in SSDT-BCKLM should i put it? Sorry i;m not an expert in SSDT

**Comment by xxxzc** [comment]
WhaterverGreen dose not use ACPI method to control brightness, brightness level is in Apple's control.
