### ISSUE TITLE
Drag function using touchpad not work on VoodooI2C v2.4

### ISSUE THREAD

**Issue by nguyentdat23** [xxxzc/xps15-9570-macos#32]
I'm using Catalina 10.15.4 right now. After update EFI with your released 2004, my touchpad cannot drag with one finger (double tap, hold and then drag to select text). I tried put back VoodooI2C v2.3 and drag function work normally.

**Comment by xxxzc** [comment]
Sorry, I didn't test this...

Please report this issue to https://github.com/alexandred/VoodooI2C/issues

**Comment by nguyentdat23** [comment]
Hello @xxxzc, after using the one built from this issue thread https://github.com/alexandred/VoodooI2C/issues/281#issuecomment-614563263
Now i can use drag funciton with one hand double tap and drag. Anyway your OC work perfect on my XPS, thanks so much.
