### ISSUE TITLE
Drm half working

### ISSUE THREAD

**Issue by carlosxfigueroa** [xxxzc/xps15-9570-macos#35]
I used to get errors when trying to launch netflix in safari or play apple tv shows, now it tries to load but instead of loading it just stays loading and never plays. here is an example
![Screen Shot 2020-04-10 at 6 36 46 PM](https://user-images.githubusercontent.com/44247379/79032298-3e41e380-7b5a-11ea-9f87-8671d2658ca2.png)

**Comment by xxxzc** [comment]
> DRM (in HDCP mode) is not supported on any IGPU-only configuration

https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/issues/1#issuecomment-603821913

**Comment by carlosxfigueroa** [comment]
> > DRM (in HDCP mode) is not supported on any IGPU-only configuration
> 
> [khronokernel/Opencore-Vanilla-Desktop-Guide#1 (comment)](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/issues/1#issuecomment-603821913)

I know this is a different issue but has hdmi audio been patched? I can get screen output but no audio

**Comment by aapw01** [comment]
Have you solved this problem?
