### ISSUE TITLE
Trackpad/cursor gets stuck/hangs/stops

### ISSUE THREAD

**Issue by Benjoyo** [xxxzc/xps15-9570-macos#36]
I installed Catalina using your OC EFI today and it is working great for the most part.
The only issue I experienced until now is that the trackpad doesn't always work right for me. 

Often, if I move the cursor around, it will suddenly stop and won't move again until I lift my finger and try again. Then after a second or two it will be stuck again and so on.
Then there are also times where I can move the cursor perfectly and it won't get stuck at all. But that is rare. 
Gestures work well, cursor feels precise and well apart from this annoying problem.

Anyone else have this problem or knows what can be the cause?

**Comment by FoundTheWOUT** [comment]
i don't know why,but try to replace the VoodooI2C.kext back to 2.3 version.

**Comment by Benjoyo** [comment]
@FoundTheWOUT thanks, I tried that today and it seems like the issue is gone. I noticed though that the multi-touch gestures don't work as smooth as before. Sometimes I have to try 2-3 times until they are recognized.

**Comment by FoundTheWOUT** [comment]
https://github.com/alexandred/VoodooI2C/issues/281

**Comment by FoundTheWOUT** [comment]
https://github.com/alexandred/VoodooI2C/issues/281

**Comment by xxxzc** [comment]
VoodooI2C 2.4.3 fixed this issue.
