### ISSUE TITLE
问个问题，你现在使用左侧发烫不，我这边挺烫的

### ISSUE THREAD

**Issue by EmiCham** [xxxzc/xps15-9570-macos#4]
不知道是啥原因，键盘左侧发热挺严重

**Comment by EmiCham** [comment]
我记得这个发烫好像是因为电源管理。可以把电源管理集成到oc内不。这段


Disable hibernation (suspend to disk or S4 sleep) macOS combines sleep and hibernation into one feature, where closing the lid initially sleeps the laptop, and eventually hibernates it. In any event, hibernation is not supported on hackintosh, and should be disabled/checked after updates.
sudo pmset -a hibernatemode 0
sudo rm -f /var/vm/sleepimage
sudo mkdir /var/vm/sleepimage # try to prevent update from re-enabling
sudo pmset -a standby 0
sudo pmset -a autopoweroff 0
    
config.plist/ACPI/SSDT/Generate/PluginType=YES
Verify that X86PlatformPlugin is loaded (see testing section)
config.plist/KernelAndKextPatches/KernelPm=YES
Enable xcpm_idle patch to prevent reboot with HWP (hardare P-state coordination)
config.plist/KernelAndKextPatches/KernelToPatch/Item n
Key=Find, Type=Data, Value=<20b9e200 00000f30>
Key=Replace, Type=Data, Value=<20b9e200 00009090>

**Comment by xxxzc** [comment]
加上 kernelpm 和 xcpm_idle 后 clover 会发热严重吗？

**Comment by xxxzc** [comment]
之前把 CPU 的设备名弄错了，应该是 _SB.PR00 而不是 _PR.CPU0，所以之前的 SSDT-PLUG 是错误的，导致 OC 下的 CPU PM 不正常= =

[SSDT-PLUG.aml.zip](https://github.com/xxxzc/xps15-9570-macos/files/4021133/SSDT-PLUG.aml.zip)

试下这个有没有改善

**Comment by EmiCham** [comment]
今天好多了啊。我第一次安装的时候用的是oc版。字体发虚、左侧发烫严重，昨天换成clover版后，发虚问题就没了，今天我看你更新了，然后我覆盖后，现在感觉挺完美的。oc版用起来咋样啊。现在

**Comment by xxxzc** [comment]
字体是你因为你用了 one-key-hidpi 嘛。
修复 CPU PM 后 OC 现在正常了。但我平常都是用 CLOVER，因为 OC 启动 Windows 会使用一些定义在 OC/config 的信息，目前不确定对 Windows 会造成什么影响。
