### ISSUE TITLE
Why is not SSDT-UIAC.aml included?

### ISSUE THREAD

**Issue by RodriMora** [xxxzc/xps15-9570-macos#41]
Isn't it neccesary for usb to work? acording to this:

https://dortania.github.io/USB-Map-Guide/intel-mapping/intel.html

"Note: Do note use either the SSDT-UIAC.aml or USBInjectAll with the USBmap.kext. This kext we just made should be used by itself with no other USB kexts besides XhciUnsupported if your system needs it. Reason for this is USBInjectAll is no longer being maintained(rest in peace Rehabman) and the USBmap.kext version is how real Macs USB map as well so as close to "Apple Like" as possible to fit the OpenCore mood."

**Comment by xxxzc** [comment]
We use [USBPorts.kext](https://github.com/xxxzc/xps15-9570-macos/blob/master/Kexts/USBPorts.kext/Contents/Info.plist) to define USB ports.

**Comment by RodriMora** [comment]
But the guide says to use either SSDT-UIAC or USBInject along USBPorts.kext right?

**Comment by xxxzc** [comment]
`SSDT-UIAC + USBInjectAll` or `USBPorts`.

**Comment by RodriMora** [comment]
> `SSDT-UIAC + USBInjectAll` or `USBPorts`.

are you sure? the wording seems to mean to use "use either the SSDT-UIAC.aml or USBInjectAll with the USBmap.kext" 
so either UIAC+USBmap or USBInjectAll+USBmap
