### ISSUE TITLE
AirDrop not working on 10.15

### ISSUE THREAD

**Issue by mahoshojoHCG** [xxxzc/xps15-9570-macos#42]
Mine is XPS-9570 4K version, with Wireless card changed to DW1830, macOS version is 10.15.3. Bluetooth and Wi-Fi works fine, but Airdrop dose not work. My friend's 9570 with DW1830 on 10.15.4, whose AirDrop also not working.
Is there any solution, or AirDrop just not works.

**Comment by mahoshojoHCG** [comment]
It seems strange, but it is now working. Anyway, thank you for your work on this config!

**Comment by leeroy-code** [comment]
> Mine is XPS-9570 4K version, with Wireless card changed to DW1830, macOS version is 10.15.3. Bluetooth and Wi-Fi works fine, but Airdrop dose not work. My friend's 9570 with DW1830 on 10.15.4, whose AirDrop also not working. Is there any solution, or AirDrop just not works.

Does your airdrop work? Mine is 10.15.7, not working
