### ISSUE TITLE
关于big sur支持

### ISSUE THREAD

**Issue by XianHe-Phil** [xxxzc/xps15-9570-macos#45]
大佬近期是否会添加对Big Sur的支持呢。我尝试使用本库的oc/clover配置，注入edid，皆无法正常启动通过虚拟机安装好的macOS 11。

**Comment by xxxzc** [comment]
不考虑，至少等到 Big Sur 发布正式版 + Acidanthera 的各种驱动更新正常后再说。

**Comment by M69W** [comment]
如果安装引导Big Sur不行，
可以通过改 [AAPL,ig-platform-id](https://github.com/xxxzc/xps15-9570-macos/blob/13ea21a86a48b674760a4cf12e95f360f7f05e6f/OC/config.plist#L156-L159) 为 `0x12345678` 来实现引导安装;

安装完毕后，如果xps 9570 屏幕是4k,
可以使用@xxxzc 写的脚本快速改EDID：https://paste.ubuntu.com/p/BNpzrQCMRg/
使用python3使用上面的脚本

@/acidanthera/bugtracker/issues/1093

**Comment by xxxzc** [comment]
群里有朋友使用 200807 的配置直接安装/升级到 Big Sur public beta，但是我一直安装失败，查了后发现应该是三星SSD比如SM961/PM961/970 EVO的问题，看 README 的说明。
