### ISSUE TITLE
Can not boot to OpenCore with Software Guard Extensions (SGX)

### ISSUE THREAD

**Issue by hoangcongtuan** [xxxzc/xps15-9570-macos#47]
Hi, thanks for your guide and EFI
I have try using your OC EFI, i can't boot to OpenCore with Intel SGX is enable, i need SGX for using finger print on Windows
With clover, this issue is not occur
I have try create OC EFI by my self, but i still can not boot to open core with SGX is enable

Sorry for my English
Thanks

**Comment by xxxzc** [comment]
You can switch SGX to Software Controlled.
