### ISSUE TITLE
SD Card Reader with new Sinetek Kext

### ISSUE THREAD

**Issue by kevinshroff** [xxxzc/xps15-9570-macos#49]
@xxxzc 
Hi,
I'm trying to test the new recently updated Sinetek SD Card Reader kext (https://github.com/cholonam/Sinetek-rtsx/releases/tag/Releases%2Fv2.3) but I noticed that whilst using this EFI (and even without the kext injected) the memory card reader does not show up at all under USB or PCI in system information. If I remember correctly it used to be visible in one of those sections when I was using a different 9570 EFI.

Is there anything in your OpenCore configuration which has disabled the SD Card reader (i.e. to save power) under macOS? Thanks!

**Comment by xxxzc** [comment]
No, you can't see SD card without that kext.

**Comment by kevinshroff** [comment]
Okay. Even with kext injected I don't see the SD Card but I guess that is not related to the EFI. Thanks

**Comment by kevinshroff** [comment]
EDIT: Tried this kext with another 9570 EFI and SD Card works perfectly so it IS related to the configuration of this EFI

**Comment by xxxzc** [comment]
Please attach your EFI, I'll find out what the problem is

**Comment by GerteN** [comment]
Have you tried "-rtsx_mimic_linux" bootarg?

**Comment by kevinshroff** [comment]
> Have you tried "-rtsx_mimic_linux" bootarg?

Yes. As previously mentioned, kext works fine in a different EFI configuration

**Comment by kevinshroff** [comment]
> Please attach your EFI, I'll find out what the problem is

[CLOVER.zip](https://github.com/xxxzc/xps15-9570-macos/files/5084423/CLOVER.zip)

**Comment by xxxzc** [comment]
[USBPorts.kext.zip](https://github.com/xxxzc/xps15-9570-macos/files/5090604/USBPorts.kext.zip)

@kevinshroff try this USBPorts.kext
