### ISSUE TITLE
opencore开机会有系统崩溃的提示

### ISSUE THREAD

**Issue by ATFieldBeast** [xxxzc/xps15-9570-macos#5]
```
Sun Jan  5 22:47:09 2020

*** Panic Report ***
panic(cpu 2 caller 0xffffff80132dd9bd): Kernel trap at 0xffffff7f942db51c, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x0000000000000119, CR3: 0x0000000856f35008, CR4: 0x00000000003626e0
RAX: 0xffffff7f96b570e0, RBX: 0xffffff805c842b80, RCX: 0xffffffa3e3fa39fc, RDX: 0x0000000000000101
RSP: 0xffffffa3e3fa39f0, RBP: 0xffffffa3e3fa3a00, RSI: 0xffffff805c842b80, RDI: 0xffffff8059e640e0
R8:  0xffffff805c842b80, R9:  0x0000000000000000, R10: 0xffffff805c842b80, R11: 0xffffff806033ce0c
R12: 0xffffffa3e3fa3b48, R13: 0x0000000000000000, R14: 0x0000000000000000, R15: 0xffffff805c842b80
RFL: 0x0000000000010286, RIP: 0xffffff7f942db51c, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000119, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xffffffa3e3fa34c0 : 0xffffff80131b057d 
0xffffffa3e3fa3510 : 0xffffff80132ec065 
0xffffffa3e3fa3550 : 0xffffff80132dd79a 
0xffffffa3e3fa35c0 : 0xffffff801315d9d0 
0xffffffa3e3fa35e0 : 0xffffff80131aff97 
0xffffffa3e3fa3700 : 0xffffff80131afde3 
0xffffffa3e3fa3770 : 0xffffff80132dd9bd 
0xffffffa3e3fa38e0 : 0xffffff801315d9d0 
0xffffffa3e3fa3900 : 0xffffff7f942db51c 
0xffffffa3e3fa3a00 : 0xffffff7f942caa40 
0xffffffa3e3fa3a20 : 0xffffff7f942c9c29 
0xffffffa3e3fa3a30 : 0xffffff8013885bb8 
0xffffffa3e3fa3a80 : 0xffffff801385a0d8 
0xffffffa3e3fa3af0 : 0xffffff7f942cab5c 
0xffffffa3e3fa3b30 : 0xffffff801388f062 
0xffffffa3e3fa3c70 : 0xffffff80132984b6 
0xffffffa3e3fa3d80 : 0xffffff80131b5dbc 
0xffffffa3e3fa3dd0 : 0xffffff8013190b31 
0xffffffa3e3fa3e50 : 0xffffff80131a524e 
0xffffffa3e3fa3ef0 : 0xffffff80132c36d7 
0xffffffa3e3fa3fa0 : 0xffffff801315e1b6 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOHIDFamily(2.0)[9A6269A4-3D7A-3798-98A3-7456E27BE1EA]@0xffffff7f942c6000->0xffffff7f94344fff

BSD process name corresponding to current thread: loginwindow
Boot args: brcmfx-country=#a agdpmod=vit9696 darkwake=1

Mac OS version:
18G2022
```

这是系统生成的错误报告
[Kernel_2020-01-05-224709_MacBook-Pro.panic.zip](https://github.com/xxxzc/xps15-9570-macos/files/4023506/Kernel_2020-01-05-224709_MacBook-Pro.panic.zip)

但是之后还是能正常进入系统

**Comment by ATFieldBeast** [comment]
另外不论是clover还是opencore，在连着typec拓展坞的时候开机都会进入dell的报错自检那个白屏界面，然后重启才能进入系统
这是自检系统生成的报错
```
<?xml version="1.0" encoding="UTF-8"?>
  <SupportAssistPrebootDiagnosticLog>
    <Schema>1.0.0</Schema>
    <LogNumber>27</LogNumber>
    <LogTimeStamp>01/05/2020 15:41:01</LogTimeStamp>
    <ePSA_Data>
      <Result>Not Reported</Result>
      <ReturnCode>BOOT_HOST_OS</ReturnCode>
      <ePSAFullVersion>4400.07</ePSAFullVersion>
      <ePSAInvocationCount>6</ePSAInvocationCount>
    </ePSA_Data>
    <BIOS_Data>
      <ErrorCategory>TYPE_C</ErrorCategory>
      <ErrorMessage><![CDATA[Thunderbolt PCIe Device Enumeration Mode Has Switched To Native.]]></ErrorMessage>
      <SOS_Available>FALSE</SOS_Available>
      <TimeOutSeconds>1</TimeOutSeconds>
    </BIOS_Data>
  </SupportAssistPrebootDiagnosticLog>

```
[diags_current.xml.zip](https://github.com/xxxzc/xps15-9570-macos/files/4023567/diags_current.xml.zip)

使用bavariancake的clover没有此问题
（另外在bavariancake的clover下可以把pe盘插在拓展坞上通过f12进入，而大佬你的在f12的界面还有bios里都读不到插在拓展坞上的pe盘

**Comment by ATFieldBeast** [comment]
是不是得改bios里的雷电3选项啊

不过我用的是typec拓展坞诶，dell wd15

**Comment by xxxzc** [comment]
第一个问题可以先更新 VoodooI2C 到 2.3 试试，也有可能是更换 kexts 造成的，前几天在测试的时候也出现了HID panic，这两天重启还是冷启都没了，也有可能是 bavariancake 配置里的 `Disable panic kext logging` 起作用了，也有可能是系统版本的问题。

开机自检这个很奇怪（我把自检关了），进入 F12 和 BIOS 的时候应该都没有启动 OC/CLOVER 吧，OC 可能会影响，但 CLOVER 没道理啊。
不能读到 pe 盘，那是否能手动添加到呢？
麻烦帮忙测试下下面几个方式看看有没有效（每个都独立测试，测试可能需要重启一两次才能体现）：
1. 删除 SSDT-TYPC，这个用于 macOS 中 typec 设备的热插拔，虽然没有也能热插拔，但是 Console 会持续报错。如果是因为这个，麻烦再测试一下 [SSDT-TYPC.aml.zip](https://github.com/xxxzc/xps15-9570-macos/files/4023673/SSDT-TYPC.aml.zip) 这个有无问题
2. 删除 USBPorts.kext 使用 bavariancake 的 SSDT-UIAC.aml 和 USBInjectAll.kext
3. 使用这个 [USBPorts.kext.zip](https://github.com/xxxzc/xps15-9570-macos/files/4023677/USBPorts.kext.zip) 试试，之前把 typec 的端口定义为 internal 了

**Comment by xxxzc** [comment]
wd15 没有用 tb 吧？我的 type-c hub 连键盘，安装盘和 HDMI 显示器没遇到问题。

**Comment by ATFieldBeast** [comment]
对啊，wd15是typec的扩展坞，但是报错是Thunderbolt PCIe Device Enumeration Mode Has Switched To Native，就很奇怪
然后L大的repo里有提到改bios里的雷电3设置什么的，就像会不会和那个有关系，我现在是出场默认的雷电3设置

bios里也没有的意思就是说在bios里想要手动添加引导都找不到盘，只能插在本子自己口上才看得到

另外我想起来了开始从bavariancake的clover切换到你的clover的时候是没有问题的，然后就从你的clover清除nvrm切换到oc，就出现了开机先进了dell的白屏自检的问题，之后再换回你的clover也这样了，但是再换回bavarian的clover又正常了

还有就是系统的报错只在你的oc下会出现，换回你的clover后也没有出现了，就只是会开机过不了自检报错

这周开始复习了所有没啥时间折腾，得稳定使用电脑所以换回bavarian的clover了，所以暂时不能帮你测试了，等下周忙完了再试试吧，上面就是我昨晚测试的时候还能回忆得起来的了，实在抱歉啊

**Comment by ATFieldBeast** [comment]
好吧，今天考了一门也不想复习，就测试了一下

在clover下：
    1.删除SSDT-TYPC.aml：可以在f12读到拓展坞上的pe盘了，也没有dell的自检报错了
    新的SSDT-TYPC.aml：仍然可以在f12读到拓展坞上的pe盘，也没有dell的自检报错
    系统正常，就没有进行2、3了

在opencore下：
    1.因为clover试过了就直接替换新的SSDT-TYPC.aml了：可以在f12读到拓展坞上的pe盘，也没有dell的自检报错
    但进入系统仍然有崩溃提示和错误报告，故：
    3.使用新的USBPorts.kext：没有崩溃提示和错误报告了
    （因为不想混用两个仓库的东西以免以后重装什么的自己也忘了搞混了，就没有进行2了，不过还好也算是系统正常了，抱歉啊）

不过在拿出机器测试的时候发现了如L大repo里的新问题[#52](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/52)（因为之前是一直合着盖子用的，今天掀开才发现），我的bios版本是1.13.0，这个bug对我来说目前没有什么大问题，因为我一直合着盖子用嘛，不过还是提交一下看看可不可以不用降bios就适配一下修好

还有就是wd15并没有完美地热拔插：开机后插入（或者插着开机拔出后再插入）usb和有线网口并没有被识别到，但是视频和音频输出正常

另外还有个小缺陷（？）就是oc开机的时候即使去掉了-v，在第一段logo读条的时候旁边也会显现一小段不会动的代码（不知道这是oc的特点还是什么奇怪的bug？），尝试过把oc的plist的debug改为0也还是存在
![IMG_3541](https://user-images.githubusercontent.com/22592396/71904706-9951ec00-31a1-11ea-8ad0-0a722c5b98a1.jpeg)

最后辛苦大佬了，谢谢大佬的付出🙏

**Comment by xxxzc** [comment]
非常感谢，通过 usb hub 连接的设备会失效这个问题我也有，查了很多都没找到答案。
显示器那个问题我试了下我的是合盖后再开盖内屏不显示，但重新插下就有了，我平常都是内屏加外屏一起使用，所以没注意这个问题。
先认真复习吧，最近也在忙毕业设计，等寒假了再看看。

**Comment by ATFieldBeast** [comment]
好，期待大佬了，再次感谢嘿嘿

**Comment by ATFieldBeast** [comment]
考完了，今天又搞鼓了一下，去掉了-v在第一段logo读条的时候旁边也会显现一小段不会动的代码的问题通过添加IgnoreTextInGraphics和它所需要的ConsoleControl解决了

不过发现在主板的dell的logo之后会出现一段很快的“ocs:no schema for consolecontrol at 0 index!”，然后才开始引导并显示苹果的logo
![IMG_3543](https://user-images.githubusercontent.com/22592396/72163138-38731f80-33fe-11ea-9fe9-5a021d9239da.png)

本来以为是我添加的ConsoleControl导致的，去掉我加的东西后（也就是大佬你原版的）还是会有，只是之前被下面的跑码吸引了没注意，尝试改也没解决

还有就是本来想添加oc界面快捷键支持的，结果照搬教程也没成功，不知道是不是和acpi有关

也都先提交到这里吧，大佬空了看看

**Comment by ATFieldBeast** [comment]
好吧，仔细看了一下那个ocs:no schema for consolecontrol at 0 index!是因为大佬你的plist里的ConsoleControl放错位置了
![屏幕快照 2020-01-11 11 55 51](https://user-images.githubusercontent.com/22592396/72198496-8709d380-3469-11ea-9792-6ab6f82a8604.png)

应该在protocols下的
![屏幕快照 2020-01-11 11 11 14](https://user-images.githubusercontent.com/22592396/72198499-95f08600-3469-11ea-8874-714a926d8d07.png)

<s>现在就没有那个报错了，只是还是会闪一个start，不知道能不能关掉（有点强迫症_(:з」∠)_</s>
![IMG_3581](https://user-images.githubusercontent.com/22592396/72198512-b15b9100-3469-11ea-8dd3-a5f9e9037221.png)

爬到了，在NVRAM里多配一个bootercfg的值就能把所有信息关掉了，强迫症一本满足
```
<key>boot-args</key>
<string>brcmfx-country=#a agdpmod=vit9696 darkwake=1</string>
<key>bootercfg</key>
<string>log=0 debug=0 level=0</string>

```

**Comment by xxxzc** [comment]
发现有可能是 Intel Power Engine (_SB_.PEPD) 这个设备导致的 USB 问题（不是你描述的问题，是我遇到的问题：USB Hub 使用一段时间后突然停止）。
你说的识别不到的问题我觉得可能是 typec 设备位置的问题，typec 设备是在 HS05，这个明显是给 USB2（HighSpeed）的。9550 的 typec 不走 XHC，USB 中不定义 typec 口依然能用，而 9570 在 USB 端口定义中删去 HS05 后是连不了设备的。

新的 release 有不少改动，可以试试。

**Comment by xxxzc** [comment]
好吧，并没有用，USB 还是会掉

**Comment by ATFieldBeast** [comment]
> 发现有可能是 Intel Power Engine (_SB_.PEPD) 这个设备导致的 USB 问题（不是你描述的问题，是我遇到的问题：USB Hub 使用一段时间后突然停止）。
> 你说的识别不到的问题我觉得可能是 typec 设备位置的问题，typec 设备是在 HS05，这个明显是给 USB2（HighSpeed）的。9550 的 typec 不走 XHC，USB 中不定义 typec 口依然能用，而 9570 在 USB 端口定义中删去 HS05 后是连不了设备的。
> 
> 新的 release 有不少改动，可以试试。

新的 release……我直接进不去系统了，重置了nvram也没用，把SSDT-TYPC和USBPorts换成你之前在issue里给我的也没用
然后换回上个版本的release可以正常使用，系统日志里有两个报告
![截屏2020-01-1816 24 01](https://user-images.githubusercontent.com/22592396/72660922-6ca69b80-3a0f-11ea-8e0a-bb44e64b88f3.png)

![截屏2020-01-1816 24 06](https://user-images.githubusercontent.com/22592396/72660937-8a740080-3a0f-11ea-99bb-de96b56296fe.png)
注意有一个是带.的隐藏文件
[Kernel_2020_01_18.zip](https://github.com/xxxzc/xps15-9570-macos/files/4080151/Kernel_2020_01_18.zip)

**Comment by xxxzc** [comment]
更改 USB 后，我需要通过 CLOVER 进一次系统后，OC 才能启动。
有可能是 OC 0.5.4 改动太多，我没配置好的缘故。

**Comment by ATFieldBeast** [comment]
啊，那我还是用着上个版本吧，有点强迫症不想混着clover和oc，之前测试完你的oc没问题之后都是格盘只用oc重装了一遍_(:з」∠)_

**Comment by xxxzc** [comment]
你这是啥子强迫症啊Orz。。。OC只是个引导，又不会影响系统文件= =不如就用 CLOVER，稳定，SSDT 和 patch 还不会影响 Windows。。。

我之前以为我隔几个月重装次 Win10 已经够强迫症了= =

**Comment by ATFieldBeast** [comment]
就……小兵那边的教程不是说clover会在系统里留东西嘛……我就直接重装的_(:_」∠)_

**Comment by ATFieldBeast** [comment]
我觉得也许不是oc没配置好，我还是用着0.5.3的oc然后只是单独更新了你新的acpi和kext（config和文件）还是进不去系统

[Kernel_2020-01-22-194948_MacBook-Pro.panic.zip](https://github.com/xxxzc/xps15-9570-macos/files/4097134/Kernel_2020-01-22-194948_MacBook-Pro.panic.zip)
这是今天的错误日志

**Comment by xxxzc** [comment]
那个 kernel panic 看不出啥，panic 是 Graphics 的问题，但是对 Graphics 的改动就是把 `enable-dpcd-max-link-rate-fix` 放到 boot arguments 里了，1080p 屏幕应该不需要这个吧。

@ATFieldBeast 试试这个
[acpi&config.zip](https://github.com/xxxzc/xps15-9570-macos/files/4101607/acpi.config.zip)

**Comment by ATFieldBeast** [comment]
> 那个 kernel panic 看不出啥，panic 是 Graphics 的问题，但是对 Graphics 的改动就是把 `enable-dpcd-max-link-rate-fix` 放到 boot arguments 里了，1080p 屏幕应该不需要这个吧。
> 
> @ATFieldBeast 试试这个
> [acpi&config.zip](https://github.com/xxxzc/xps15-9570-macos/files/4101607/acpi.config.zip)

还是不行，这是你这个的报错
[Kernel_2020-01-23-181841.zip](https://github.com/xxxzc/xps15-9570-macos/files/4102523/Kernel_2020-01-23-181841.zip)（又有一个.文件

（我确实是1080p的，但是已经去掉了-igfxmlr

（对了你的bios版本是多少啊，和这个会有关系不，不是说bios更新也有可能导致ssdt发生变化啥的么

还有我发现睡眠唤醒后wifi网速会变得特别慢，睡前11m/s，唤醒后50k/s这样，重启之后才正常，不过我还用的是0.5.3的release，不知道这个在新版有修复不（之前在学校一直拓展坞插着网线，回家只有wifi了才发现这个

**Comment by xxxzc** [comment]
> 对啊，wd15是typec的扩展坞，但是报错是Thunderbolt PCIe Device Enumeration Mode Has Switched To Native，就很奇怪
然后L大的repo里有提到改bios里的雷电3设置什么的，就像会不会和那个有关系，我现在是出场默认的雷电3设置

`Thunderbolt PCIe Device Enumeration Mode Has Switched To Native` 不是报错，只是一个提示，在 BIOS 里取消 Thunderbolt 自动选择，直接选择 `Native` 或者 `BIOS Assist` 就不会有这个提示了。

> （对了你的bios版本是多少啊，和这个会有关系不，不是说bios更新也有可能导致ssdt发生变化啥的么

我的 BIOS 是最新的。

> 还有我发现睡眠唤醒后wifi网速会变得特别慢，睡前11m/s，唤醒后50k/s这样，重启之后才正常，不过我还用的是0.5.3的release，不知道这个在新版有修复不（之前在学校一直拓展坞插着网线，回家只有wifi了才发现这个

WiFi 网速问题没遇到，确定设置- Energy Saver 节能器里都取消勾选了吗？我记得是勾选 Power Nap 会影响唤醒后的网速。

---

你用扩展坞有遇到 USB2.0 设备突然失效的问题吗？我在 LuletterSoul 那也看到有这个问题 https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/17 ，尝试了各种 patches 都没用，现在只能怀疑是我的外接键盘或者 HUB 的问题了

**Comment by ATFieldBeast** [comment]
> `Thunderbolt PCIe Device Enumeration Mode Has Switched To Native` 不是报错，只是一个提示，在 BIOS 里取消 Thunderbolt 自动选择，直接选择 `Native` 或者 `BIOS Assist` 就不会有这个提示了。
> 
嗯嗯，我发了issue后就尝试改了，之后就没出现了
> 
> 我的 BIOS 是最新的。
> 
好的，谢谢，我觉得大佬你的readme里可以像bavariancake的repo把bios版本也加上，这样信息更完全（一个小小的建议
> 
> WiFi 网速问题没遇到，确定设置- Energy Saver 节能器里都取消勾选了吗？我记得是勾选 Power Nap 会影响唤醒后的网速。
> 
都去掉了
![截屏2020-01-2616 35 39](https://user-images.githubusercontent.com/22592396/73132794-b9672380-405a-11ea-9271-bcf05aa430db.png)
![截屏2020-01-2616 35 43](https://user-images.githubusercontent.com/22592396/73132795-b9672380-405a-11ea-9c0f-55ed4377d563.png)
（是这样设置吧？但是就是会掉网速
> 
> 你用扩展坞有遇到 USB2.0 设备突然失效的问题吗？我在 LuletterSoul 那也看到有这个问题 [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#17](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/17) ，尝试了各种 patches 都没用，现在只能怀疑是我的外接键盘或者 HUB 的问题了
> 
我一直没有遇到这个问题诶，最开始用的LuletterSoul的，之后用的bavariancake的，现在用的你的都一直没有这个问题，我用的wd15后面的俩USB2.0的口接的鼠标键盘，没有出现突然失效的问题
![58612c1cb5e1d1892 png_e680 jpg](https://user-images.githubusercontent.com/22592396/73132858-a9037880-405b-11ea-8219-90f4e1a0f301.png)

**Comment by ATFieldBeast** [comment]
> WiFi 网速问题没遇到，确定设置- Energy Saver 节能器里都取消勾选了吗？我记得是勾选 Power Nap 会影响唤醒后的网速。
> 
![截屏2020-01-2717 46 50](https://user-images.githubusercontent.com/22592396/73164792-948fb080-412d-11ea-956b-50d79714ee20.png)

<s>好像按这里的说法把蓝牙里的唤醒关掉了没有变慢了</s>
<s>晚上睡觉的时候再长时间睡眠试试看</s>
![截屏2020-01-2810 18 35](https://user-images.githubusercontent.com/22592396/73230803-5f30a480-41b9-11ea-9f8c-172b9d9ead41.png)

<s>好像确实这样有解决网速唤醒变慢，应该是有效的</s>
之前没有变慢是我顺便测试睡眠掉电，就拔掉电源睡眠的
今天插着电源睡眠唤醒后又复现了
好像和蓝牙选项没有关系而是电源状态
![截屏2020-01-2816 41 18](https://user-images.githubusercontent.com/22592396/73248370-d122e100-41ed-11ea-8558-52a8de839373.png)

29号，移除电源使用电池长时间睡眠后唤醒网速正常
应该就是连接电源的时候有什么bug吧

**Comment by tofuliang** [comment]
各位大佬要不要拉个群一齐讨论下~我在GitHub上找到 [smallssnow/XPS9570-8570H-macos](https://github.com/smallssnow/XPS9570-8570H-macos) 也有硬核输出啊。

[OldDream/Dell-XPS-15-9570-macOS-Mojave](https://github.com/OldDream/Dell-XPS-15-9570-macOS-Mojave) 这里的OC有很多PCI位置的补丁，
但是我不懂的怎么验证是否正确，而且`master上`的EFI下载下来，进入的是CLOVER。

PS.
我根据 [https://khronokernel.github.io/Opencore-Vanilla-Desktop-Guide/extras/msr-lock.html](https://khronokernel.github.io/Opencore-Vanilla-Desktop-Guide/extras/msr-lock.html) 把MSR解锁了，
BIOS版本是1.13. 具体位置是 `setup_var 0x5BD 0x00`
看[reddit](https://www.reddit.com/r/Dell/comments/eojrsy/dell_xps_15_9570_system_bios_115/) 说1.14引入了一个CPU C-state的bug,但是1.15并没有修复。

**Comment by ATFieldBeast** [comment]
> 各位大佬要不要拉个群一齐讨论下~我在GitHub上找到 [smallssnow/XPS9570-8570H-macos](https://github.com/smallssnow/XPS9570-8570H-macos) 也有硬核输出啊。
> 
> [OldDream/Dell-XPS-15-9570-macOS-Mojave](https://github.com/OldDream/Dell-XPS-15-9570-macOS-Mojave) 这里的OC有很多PCI位置的补丁，
> 但是我不懂的怎么验证是否正确，而且`master上`的EFI下载下来，进入的是CLOVER。
> 
> PS.
> 我根据 https://khronokernel.github.io/Opencore-Vanilla-Desktop-Guide/extras/msr-lock.html 把MSR解锁了，
> BIOS版本是1.13. 具体位置是 `setup_var 0x5BD 0x00`
> 看[reddit](https://www.reddit.com/r/Dell/comments/eojrsy/dell_xps_15_9570_system_bios_115/) 说1.14引入了一个CPU C-state的bug,但是1.15并没有修复。

9570有一个黑苹果群的，929644389，不过群里的人版本更新啥的都是直接一股脑打包传群文件，感觉不如github版本管理来得好，当然如果是讨论还是挺方便的，想要加的就申请一下吧

（刚才点comment不小心点到close了，然后就reopen了一下_(:з」∠)_

**Comment by tofuliang** [comment]
> > 各位大佬要不要拉个群一齐讨论下~我在GitHub上找到 [smallssnow/XPS9570-8570H-macos](https://github.com/smallssnow/XPS9570-8570H-macos) 也有硬核输出啊。
> > [OldDream/Dell-XPS-15-9570-macOS-Mojave](https://github.com/OldDream/Dell-XPS-15-9570-macOS-Mojave) 这里的OC有很多PCI位置的补丁，
> > 但是我不懂的怎么验证是否正确，而且`master上`的EFI下载下来，进入的是CLOVER。
> > PS.
> > 我根据 https://khronokernel.github.io/Opencore-Vanilla-Desktop-Guide/extras/msr-lock.html 把MSR解锁了，
> > BIOS版本是1.13. 具体位置是 `setup_var 0x5BD 0x00`
> > 看[reddit](https://www.reddit.com/r/Dell/comments/eojrsy/dell_xps_15_9570_system_bios_115/) 说1.14引入了一个CPU C-state的bug,但是1.15并没有修复。
> 
> 9570有一个黑苹果群的，929644389，不过群里的人版本更新啥的都是直接一股脑打包传群文件，感觉不如github版本管理来得好，当然如果是讨论还是挺方便的，想要加的就申请一下吧
> 
> （刚才点comment不小心点到close了，然后就reopen了一下_(:з」∠)_

那个群我早就加了，但是一段时间下来后，感觉营养价值不高，就没有关注了。
主要是人多了以后太容易跑题了。但是在GitHub这里，各自都搞一个repo，知晓并且参与进来的人又分散开了。

[macOS-IOElectrify](https://github.com/the-darkvoid/macOS-IOElectrify) 貌似是雷电三热插拔的，不知道要怎么适配？

**Comment by ATFieldBeast** [comment]
> 那个 kernel panic 看不出啥，panic 是 Graphics 的问题，但是对 Graphics 的改动就是把 `enable-dpcd-max-link-rate-fix` 放到 boot arguments 里了，1080p 屏幕应该不需要这个吧。
> 
> @ATFieldBeast 试试这个
> [acpi&config.zip](https://github.com/xxxzc/xps15-9570-macos/files/4101607/acpi.config.zip)

今天闲得没事就把更新的acpi一项一项地替换排错，都没有问题；然后把config剩下的不同也改了，替换oc0.5.4也没问题，不过这次我没动DeviceProperties里的配置，那应该就是你去掉的enable-dpcd-max-link-rate-fix那些的问题了（上面你说SSDT-DDEV对USB失效没用（我也没有这个问题）所以这个也就没有添加）

**Comment by xxxzc** [comment]
@ATFieldBeast  所以现在 OC 能启动了么

**Comment by xxxzc** [comment]
@ATFieldBeast 我似乎找到问题了！！今天更新系统后，我的 OC 也进不去了，然后发现 report 里的 bootarg 不是我现在在用的，就很奇怪。

试了很久发现是 `RequestBootVarRouting` 的问题，把这一项设为 false 或者删掉试试。

**Comment by ATFieldBeast** [comment]
@xxxzc 不行，我还是得在DeviceProperties里加上max-link-rate的参数才能启动，不然就直接卡住重启（1080p）
```
<key>dpcd-max-link-rate</key>
<data>
CgAAAA==
</data>
<key>enable-dpcd-max-link-rate-fix</key>
<data>
AQAAAA==
</data>
```

不过你说的RequestBootVarRouting的问题没有遇到

现在差不多就差连接电源唤醒后网速很慢的问题和c口的热拔插（这个现在被困在家里测不了emmmm）就比较完美了
（上面有详细对照测试

还有这次新的release200130是把显存改回1.5g了么，还是我出bug了
![截屏2020-01-3012 04 59](https://user-images.githubusercontent.com/22592396/73419105-e5372180-4358-11ea-8e1e-c103a9893c0b.png)

（另外一直想问，我是集显版没有独显，可以不加DGPU么

发现不加fakepciid音频还是会掉，我又自己加回来了
![截屏2020-01-3012 23 25](https://user-images.githubusercontent.com/22592396/73420185-97bcb380-435c-11ea-9aad-b978ec435b56.png)

**Comment by xxxzc** [comment]
好的，我把 max-link-rate 加回去，然后加个描述吧。

之前我睡眠有问题改了一些，忘了把显存加回去了。

网速问题可以把 FakePCIID_Broadcom_WiFi.kext 也加上去试试。

集显版可以不加 DGPU。

音频删掉 fakepciid 后第一次重启肯定会掉，得多重启几次看看。（我也有点强迫症，kexts 里就只有这个是 bitbucket 的了，期望 AppleALC 能彻底解决这个问题）

**Comment by xxxzc** [comment]
关于 USB，这是 ACPI 文档对接口的描述：
<img width="889" alt="Screen Shot 2020-01-30 at 2 12 54 PM" src="https://user-images.githubusercontent.com/22726929/73424716-9eeabe00-436a-11ea-9b5c-6354840db436.png">

9570 DSDT 里的接口定义大都不符合这个规范，因为 type-c 只有 HS05，所以我设置成 0x08 了，但是 macos 里是当作 0x02 ExpressCard 来处理，所以设置成 0x02 说不定也成。手头没有 typec hub，回学校再说。

**Comment by ATFieldBeast** [comment]
> 好的，我把 max-link-rate 加回去，然后加个描述吧。
> 
> 之前我睡眠有问题改了一些，忘了把显存加回去了。
> 
> 网速问题可以把 FakePCIID_Broadcom_WiFi.kext 也加上去试试。
> 
> 集显版可以不加 DGPU。
> 
> 音频删掉 fakepciid 后第一次重启肯定会掉，得多重启几次看看。（我也有点强迫症，kexts 里就只有这个是 bitbucket 的了，期望 AppleALC 能彻底解决这个问题）


好的辛苦大佬了

经测试 FakePCIID_Broadcom_WiFi.kext 没有作用,网速还是会掉
（我的wifi信息是这样的，有很多null，不知道有没有关系
![截屏2020-01-3020 15 19](https://user-images.githubusercontent.com/22592396/73449535-5b11ac00-439e-11ea-89b9-9e68d534df52.png)


另外删掉 fakepciid 多次重启后，除去第一次音频还是掉了一次，看来还是不能删掉

**Comment by ATFieldBeast** [comment]
今天在oc群看到说掉音频是applealc还没有解决，不过单独重新加载applehda也行，就不用重启了
![截屏2020-02-0111 00 45](https://user-images.githubusercontent.com/22592396/73586198-a930c780-44e4-11ea-9042-d0ba53336720.png)
![截屏2020-02-0111 01 06](https://user-images.githubusercontent.com/22592396/73586201-afbf3f00-44e4-11ea-9051-471a9b2a3fb9.png)

然后想起之前我拓展坞的有线网卡的驱动刚升15的时候也有掉驱动的bug，他们是写了个重新加载驱动的脚本来强制加载一遍驱动
![截屏2020-02-0111 04 01](https://user-images.githubusercontent.com/22592396/73586225-00369c80-44e5-11ea-9a3f-9204b995cd45.png)
然后弄了个开机自动的
![截屏2020-02-0111 04 16](https://user-images.githubusercontent.com/22592396/73586228-09276e00-44e5-11ea-84cc-f929e6df993b.png)
或许在applealc没有解决前applehda也可以这么弄个，就可以不用fakepciid了（虽然还是不很优雅

（不过我现在还是用着fakepciid的，懒得再改了，下次更新efi的时候再一道试一下

**Comment by ATFieldBeast** [comment]
看更新日志也不知道是这次更新了啥的原因，貌似插电睡醒后网速没有问题了，这样就好像没啥大问题了，这个先就可以关掉了

**Comment by wtdcode** [comment]
> 非常感谢，通过 usb hub 连接的设备会失效这个问题我也有，查了很多都没找到答案。
> 显示器那个问题我试了下我的是合盖后再开盖内屏不显示，但重新插下就有了，我平常都是内屏加外屏一起使用，所以没注意这个问题。
> 先认真复习吧，最近也在忙毕业设计，等寒假了再看看。

你USB的问题解决了吗 :)

**Comment by xxxzc** [comment]
> 你USB的问题解决了吗 :)

@wtdcode 没有，失效的时候根本没有日志，IOJones里设备信息也没有变化，尝试了各种方法都没用，放弃了，只用自带的 USB 口连鼠标键盘。

群里有些朋友表示没有遇到这个问题，很奇怪。

**Comment by wtdcode** [comment]
> > 你USB的问题解决了吗 :)
> 
> 
> 
> @wtdcode 没有，失效的时候根本没有日志，IOJones里设备信息也没有变化，尝试了各种方法都没用，放弃了，只用自带的 USB 口连鼠标键盘。
> 
> 
> 
> 群里有些朋友表示没有遇到这个问题，很奇怪。

@xxxzc 我也是，完全没有任何日志，而且我在另一台 deskmini 310 上也出现了相同的症状。我猜测很多人没遇到的原因可能是没有长时间开机。

另外有三点我觉得需要注意。第一点是在所有usb挂掉的时候，我的da300的网口仍然work，现在人不在学校没有设备但我印象里这个网口是在usb总线的。第二点是在我的deskmini上挂掉的频率要低的多（虽然开机时间更长），而且每次2.0都可以用但是3.0不行。第三点是我的xps9570有一段时间没出现这个bug了，不知道和系统升级有没有关系。
