### ISSUE TITLE
HDMI audio failure and 3.5mm mic failure

### ISSUE THREAD

**Issue by RayZhang13** [xxxzc/xps15-9570-macos#51]
I experienced 3.5mm mic failure as there is no input from the headphone jack after upgrading to macOS 10.15.6.
After upgrading to macOS Big Sur, things got worse. HDMI audio output is currently unable to detect.
I've tried different layouts like 30, 72, 99... Still not working.
IDK what's going on, they are supposed to work before. 
Any suggestions or help would be great. BTW thx for the efi configuration, it's working fine on my laptop.
![Screen Shot 2020-08-15 at 9 05 33 PM](https://user-images.githubusercontent.com/48504648/90312966-17961e00-df3b-11ea-9ca6-34192d83270b.png)
![Screen Shot 2020-08-15 at 8 56 58 PM](https://user-images.githubusercontent.com/48504648/90312971-1a910e80-df3b-11ea-9f28-cfa7f35f3e9d.png)

**Comment by jaromeyer** [comment]
is combojack working?

**Comment by adityahota** [comment]
@jaromeyer ComboJack works for me. I am able to use the aux jack on Big Sur.

However, HDMI audio is broken for me on 10.15.6 and 11.0. @xxxzc can you confirm if you have the same issue?

**Comment by RayZhang13** [comment]
> @jaromeyer ComboJack works for me. I am able to use the aux jack on Big Sur.
> 
> However, HDMI audio is broken for me on 10.15.6 and 11.0. @xxxzc can you confirm if you have the same issue?

HDMI audio works if you boot up the laptop with the lid closed. I've tried a couple of times.

**Comment by RayZhang13** [comment]
> is combojack working?

Combo jack is not working for me.😭
idk what's going on. I've tried different audio layout and installed combo jack...Nothing happened.

**Comment by jaromeyer** [comment]
Im not sure about audio over HDMI, because I have never used it, but the audio jack should work properly with ComboJack. Do you get a popup when plugging in headphones?

**Comment by RayZhang13** [comment]
> Im not sure about audio over HDMI, because I have never used it, but the audio jack should work properly with ComboJack. Do you get a popup when plugging in headphones?

Yes. Of course I do, I can get audio output from the jack and the pop-up is working just fine. The problem is that that I can't get any audio output from my earphones. So that I have to use the built-in mic. I also can't see any output signals on the sound setting panel.
