### ISSUE TITLE
Hdmi Audio no longer working on 10.15.6 and 11.0

### ISSUE THREAD

**Issue by adityahota** [xxxzc/xps15-9570-macos#54]
After updating to 10.15.6, I am no longer able to get audio over HDMI or DP. I tried injecting the device ID as was previously being done and tried with FakePCIID_Intel_HDMI_Audio kext but no luck.

Is this issue there for anyone else?

**Comment by xxxzc** [comment]
My HDMI audio is working fine without device-id and fakepciid, hmm...

**Comment by adityahota** [comment]
@xxxzc I can try again with a clean install. I'll let you know the results.

Which versions did you run it on?

**Comment by adityahota** [comment]
@xxxzc I did a clean install of 10.15.6 and audio did not work when hotplugging.

**Comment by carlosxfigueroa** [comment]
same here audio not working, how can I disable the fixes you implemented 

close this issue, seems the fix is dead from 10.15.6 and up they are looking for a new way to patch

**Comment by xxxzc** [comment]
The audio patch is still working for me in 10.15.7...

---

My bad. It seems that OpenCore cannot apply that patch correctly, I'm using CLOVER and HDMI audio is working fine.

@adityahota @carlosxfigueroa

**Comment by adityahota** [comment]
I came across [this](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/issues/28#issuecomment-690028002) patch and rebuilt the latest AppleALC driver. Now HDMI audio is working perfectly! I have tested on Big Sur so far, but someone in the thread reported it working on 10.15.6 on their laptop as well.

Going forward, I am not sure if there is a way to inject this change so we don't have to recompile the driver, or if we can submit this patch to be permanently included in AppleALC. @xxxzc what are your thoughts on this? This was my first time recompiling the driver haha

<img width="326" alt="Screen Shot 2020-10-03 at 11 33 56 AM" src="https://user-images.githubusercontent.com/12516225/94995877-1e223880-056f-11eb-91b7-2bdd70798ffe.png">

@carlosxfigueroa if you want to try out my patched kext, it's attached.
[AppleALC.kext.zip](https://github.com/xxxzc/xps15-9570-macos/files/5321930/AppleALC.kext.zip)

**Comment by carlosxfigueroa** [comment]
> I came across [this](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/issues/28#issuecomment-690028002) patch and rebuilt the latest AppleALC driver. Now HDMI audio is working perfectly! I have tested on Big Sur so far, but someone in the thread reported it working on 10.15.6 on their laptop as well.
> 
> Going forward, I am not sure if there is a way to inject this change so we don't have to recompile the driver, or if we can submit this patch to be permanently included in AppleALC. @xxxzc what are your thoughts on this? This was my first time recompiling the driver haha
> 
> <img alt="Screen Shot 2020-10-03 at 11 33 56 AM" width="326" src="https://user-images.githubusercontent.com/12516225/94995877-1e223880-056f-11eb-91b7-2bdd70798ffe.png">
> 
> @carlosxfigueroa if you want to try out my patched kext, it's attached.
> [AppleALC.kext.zip](https://github.com/xxxzc/xps15-9570-macos/files/5321930/AppleALC.kext.zip)

ill give it a shot now!

edit: works very well, how did you patch the kext?

**Comment by adityahota** [comment]
Awesome, glad it's working for you!

I cloned the AppleALC source and modified the file in Resources/Controllers.plist. The post I linked to includes a git diff which is the raw data you can change in the Controllers.plist file--then I just recompiled the kext in Xcode (getting all the dependencies right was a pain, make sure you have the 10.15 SDK and a debug version of Lilu.kext).

**Comment by fkscott** [comment]
I tried using this kext, but still have no options to switch to my monitor's audio in Catalina 10.15.6. I am using the EFI fhd config from [jaromeyer's](https://github.com/jaromeyer/XPS9570-Catalina/) repository as a start. Do I need to rebuild the kext for my specific hardware?

**Comment by attilagyorffy** [comment]
Have you tried resetting your kext cache and then restarting?
sudo kextcache -i /

Check once this is complete, restart your system and try again. It may
solve the problem. Good luck!

**Comment by adityahota** [comment]
I don’t believe you need to recompile the kext. Are you certain that the monitor supports audio? If so, try unplugging and replugging or sleeping and waking your laptop with the HDMI cable plugged in. 

Also try resetting the kext cache as pointed out just now above 

@attilagyorffy did it work for you?

**Comment by fkscott** [comment]
The monitor does support HDMI audio. Both my Windows PC and another Macbook pass through the audio without an issue. Unfortunately resetting my kext cache did not help. Monitor works just fine, but I don't have the ability to change to the monitor's output. Are there any other troubleshooting steps I can take, or should I consider downgrading to 10.15.5 if I really want HDMI audio working?

**Comment by adityahota** [comment]
Perhaps try loading macOS with this EFI and see if it works. Maybe it’s an
EFI specific issue since this kext seems to be working for me.

**Comment by attilagyorffy** [comment]
> I don’t believe you need to recompile the kext. Are you certain that the monitor supports audio? If so, try unplugging and replugging or sleeping and waking your laptop with the HDMI cable plugged in.
> 
> Also try resetting the kext cache as pointed out just now above
> 
> @attilagyorffy did it work for you?

I haven't had the time to test this out. I'm in the middle of building my own EFI for Big Sur with reproducible, documented steps (individual commits) for clarity. Once I've got the OS running, I will revisit the audio issues.

**Comment by xxxzc** [comment]
> The audio patch is still working for me in 10.15.7...
> 
> My bad. It seems that OpenCore cannot apply that patch correctly, I'm using CLOVER and HDMI audio is working fine.
> 
> @adityahota @carlosxfigueroa

Seems OpenCore 0.6.3 can use that patch, HDMI audio is working fine, can you try the latest release? @attilagyorffy  @adityahota 

<img width="780" alt="Screen Shot 2020-11-16 at 12 55 48 AM" src="https://user-images.githubusercontent.com/22726929/99192889-68bee380-27b0-11eb-84a0-1247acf36780.png">

**Comment by adityahota** [comment]
I just tried the latest version of AppleALC with OpenCore 0.6.3 and HDMI audio still didn't work for me 😕

EDIT: Just saw there was a new release of the EFI. I haven't had a chance to rest your release out yet (I can get to it next weekend) but I did update the kexts manually and added in the HDMI changes over the past two months. Perhaps it will work with your EFI, and I will let you know. For now, the old AppleALC kext that I build seems to be working fine for HDMI audio.

**Comment by carlosxfigueroa** [comment]
> I came across [this](https://github.com/tctien342/Dell-Inspiron-7591-Hackintosh/issues/28#issuecomment-690028002) patch and rebuilt the latest AppleALC driver. Now HDMI audio is working perfectly! I have tested on Big Sur so far, but someone in the thread reported it working on 10.15.6 on their laptop as well.
> 
> Going forward, I am not sure if there is a way to inject this change so we don't have to recompile the driver, or if we can submit this patch to be permanently included in AppleALC. @xxxzc what are your thoughts on this? This was my first time recompiling the driver haha
> 
> <img alt="Screen Shot 2020-10-03 at 11 33 56 AM" width="326" src="https://user-images.githubusercontent.com/12516225/94995877-1e223880-056f-11eb-91b7-2bdd70798ffe.png">
> 
> @carlosxfigueroa if you want to try out my patched kext, it's attached.
> [AppleALC.kext.zip](https://github.com/xxxzc/xps15-9570-macos/files/5321930/AppleALC.kext.zip)

by chance did you patch the latest kext?

**Comment by adityahota** [comment]
I haven't patched the latest kext but the version I built is still working with the latest OpenCore (and HDMI audio works too). I can patch a new version in a couple weeks if you'd like but I think all should still work till then.

**Comment by carlosxfigueroa** [comment]
> I haven't patched the latest kext but the version I built is still working with the latest OpenCore (and HDMI audio works too). I can patch a new version in a couple weeks if you'd like but I think all should still work till then.

Any update on this? Or a mini guide i can follow?

**Comment by xxxzc** [comment]
I built one from latest. @carlosxfigueroa [AppleALC.kext.zip](https://github.com/xxxzc/xps15-9570-macos/files/5792841/AppleALC.kext.zip)

**Comment by Drowningfish223** [comment]
The kexts work for me if I boot without the monitor connected. One quirk is that HDMI audio shows up as displayport audio. Thanks for the fix!
