### ISSUE TITLE
4K display running at 48Hz

### ISSUE THREAD

**Issue by golimpio** [xxxzc/xps15-9570-macos#55]
This is just a question not an issue as it's well documented in your readme file.

Is any known workaround for the 48Hz hack on Big Sur? I didn't know about it until I started testing Big Sur on my XPS 9550. I'm doing some google about it, but if you could please point me to any webpage talking about it I appreciate it.

Thank you for sharing your work.

**Comment by LinhNC** [comment]
I have same problem with my 4k XPS 9570 too, It's topic talk about it: 
https://github.com/jardenliu/XPS15-9560-Catalina/issues/157
Now seems we don't have any solution to solve it.

**Comment by adityahota** [comment]
Rejoice!! Looks like the latest WEG commit has fixed this issue. @xxxzc just updated the repo--thank you so much! Can't wait to test it out tomorrow.

**Comment by LinhNC** [comment]
> Rejoice!! Looks like the latest WEG commit has fixed this issue. @xxxzc just updated the repo--thank you so much! Can't wait to test it out tomorrow.

Working perfect, many thanks^^
