### ISSUE TITLE
update.py in release package doesn't have the big sur inject edid function for 4k.

### ISSUE THREAD

**Issue by Drowningfish223** [xxxzc/xps15-9570-macos#59]
@xxxzc,

Thanks for including the info for 4k display users on Big Sur! I was having kernel panics in the installer due to an invalid link rate causing division by zero, and your fix worked perfectly for me. The only issue is that the update.py in the latest release won't allow me to switch the edid. I had to grab the raw version of the update.py in the master branch. If anyone wants to do the fix manually, add 

**AAPL00,override-no-connect** as a data key under the graphics device properties in your config.plist. For the value, copy and paste this EDID: 

00FFFFFF FFFFFF00 4D10B914 00000000 161D0104 A5221378 0EF684AD 5035BF24 01565600 00000101 01010101 01010101 01010101 0101A6A6 00A0F070 3E803020 350058C2 10000018 00000000 00000000 00000000 00000000 00000000 00FE004E 35563843 804C5131 35364431 00000000 00024103 32011200 000B010A 202000C6

From my understanding, an EDID is how a display identifies itself for the OS. This EDID will force the display to run at 48hz.

You should be able to boot after that fix.

Good luck!

**Comment by xxxzc** [comment]
Updated.
