### ISSUE TITLE
Big Sur beta10 无法升级

### ISSUE THREAD

**Issue by gujiangjiang** [xxxzc/xps15-9570-macos#60]
我的固态是SM961戴尔版

Beta1到Beta9都没问题，直接升级，Beta10不行，很奇怪，升级不行，全新安装不行，只要在OpenCore页面点击beta10的install选项回车，就会黑屏，-v也没有任何显示，直接黑屏，然后过5s左右回到OpenCore界面。。。。

**Comment by xxxzc** [comment]
bugtracker 上有个 issue 说 SecureBootModel 要 disabled，有用么

**Comment by gujiangjiang** [comment]
> bugtracker 上有个 issue 说 SecureBootModel 要 disabled，有用么

没用，这个beta9就设置为disabled了，升级到beta10依然不行

**Comment by xxxzc** [comment]
用上正式版了

**Comment by gujiangjiang** [comment]
哎，我这里还是不行，我是9550，从beta10到正式版，一路上我都试过都不行，直接黑屏5s然后返回到OC界面，全新安装也不行，我真的也是无解了，然后我看到有人跟我一样的情况。

http://bbs.pcbeta.com/viewthread-1875359-1-1.html

头疼

**Comment by gujiangjiang** [comment]
用了你的OC配置，一样的情况。。。黑屏5s之后返回OC界面。。。


![IMG_5315](https://user-images.githubusercontent.com/13273955/99240439-723f5e80-2837-11eb-8401-76cfd9ffb885.jpg)

**Comment by xxxzc** [comment]
我还是觉得很有可能是SM961 PM961 的问题，之前beta时候怎么样都装不上，换了SN550就装上了，这次更是一点问题都没遇到，之前远景上也有个帖说这个问题，不知道你有没看到，他帮别人装，其他同配置，就sm961的装不上

**Comment by gujiangjiang** [comment]
不至于吧，至少beta1到beta9都没问题的。。。尴尬，这下彻底与bigsur无缘了看来

**Comment by GlowsSama** [comment]
> 不至于吧，至少beta1到beta9都没问题的。。。尴尬，这下彻底与bigsur无缘了看来

这个

> 哎，我这里还是不行，我是9550，从beta10到正式版，一路上我都试过都不行，直接黑屏5s然后返回到OC界面，全新安装也不行，我真的也是无解了，然后我看到有人跟我一样的情况。
> 
> http://bbs.pcbeta.com/viewthread-1875359-1-1.html
> 
> 头疼

这个远景楼主是我   不过我不是961而是海力士的一款ssd  也是9550

**Comment by xxxzc** [comment]
@gujiangjiang 今天试了下载 XPS15-9550-OC-BRCM-201116.zip，只把 device properties 和三码改成 9570 的，还是能正常进 big sur，emm...

**Comment by gujiangjiang** [comment]
@qw1363673600 解决没？

@xxxzc 我再试试看，十分怀疑是分配内存的问题

**Comment by xxxzc** [comment]
> @qw1363673600 解决没？
> 
> @xxxzc 我再试试看，十分怀疑是分配内存的问题

opencore好像可以换memoryfix，试试加上clover的那个v3？

**Comment by gujiangjiang** [comment]
@xxxzc 试过menoryfix，直接禁行，估计不兼容11.0了
但是我测试过，勾选那个“DevirtualiseMmio”这个选项，不黑屏了，但是直接禁行，-v也有代码了，但是就是禁行进不去，明显是卡内存了，去掉这个选项，别的选项无论怎么组合都是黑屏5s返回OC界面，所以我才怀疑是内存分配的问题

**Comment by xxxzc** [comment]
OsxAptioFix3Drv.efi 
[OsxAptioFix3Drv.efi.zip](https://github.com/xxxzc/xps15-9570-macos/files/5551435/OsxAptioFix3Drv.efi.zip)

这个试过吗

**Comment by gujiangjiang** [comment]
@xxxzc 我试试看哈
