### ISSUE TITLE
Support for macOS big sur

### ISSUE THREAD

**Issue by imraan-go** [xxxzc/xps15-9570-macos#61]
Since the MacOS big sur 11.0.1 [release candidate](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes) is out, are you planning to release updated EFI ? the latest release is from August.

**Comment by imraan-go** [comment]
Official Big Sur is released. Will there be a compatible EFI? Also did PM961 Stopped working in Big Sur?

**Comment by xxxzc** [comment]
You can try my latest release, but I can't make any guarantees.

edit: My 9570 OTA to Big Sur flawlessly

**Comment by imraan-go** [comment]
The problem with PM961  still exists? If yes , is it an OTA only bug? cause i wanna clean install big sur on PM961

**Comment by xxxzc** [comment]
You can try, I'm also wondering  if it's SSD's problem.

**Comment by xxxzc** [comment]
> The problem with PM961 still exists? If yes , is it an OTA only bug? cause i wanna clean install big sur on PM961

In my previous attempts on big sur beta, not only OTA.

**Comment by imraan-go** [comment]
I think this will fix the 4k 60hz Issue on internal display? https://github.com/acidanthera/WhateverGreen/commit/9b68d9fba30a08f72dfbfe4cf82f674039f531ac

@xxxzc what do you think?

**Comment by xxxzc** [comment]
One of my friend confirmed that it works. The brightness may not be normal in the first few minutes after boot and will recover automatically after a while.

**Comment by imraan-go** [comment]
Finally I can upgrade to Big Sur 😃  Are you planning for a new release with this patch before new release of WEG?

**Comment by xxxzc** [comment]
Yep, maybe this weekend. I am using 15.7 currently.

**Comment by imraan-go** [comment]
I've clean installed Big Sur 11.1 on my PM961. Everything is working properly. With the latest pull request, backlight is working on 4k@60hz.

**Comment by imraan-go** [comment]
everything works fine with new release. Closing this issue.
