### ISSUE TITLE
无法启动big sur安装程序

### ISSUE THREAD

**Issue by mahoshojoHCG** [xxxzc/xps15-9570-macos#62]
- 全新安装
- 4K版，硬盘不是三星的
- 在配置文件中和Kext文件中删除所有bcrm的kext（没有使用博通网卡），安装时也没有加载intelwifi的kext
- 在安装前所有kext以及OpenCore已经更新到最新版本
- linux中使用xrandr获取edid为`00ffffffffffff004d108d1400000000051c0104a52213780e522eaa5335bc250c5054000000010101010101010101010101010101014dd000a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a2020000a`，经过仓库中update.py中相同的算法算得修改后的edid为`00ffffffffffff004d108d1400000000051c0104a52213780e522eaa5335bc250c505400000001010101010101010101010101010101a6a600a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a202000db`，base64为`AP///////wBNEI0UAAAAAAUcAQSlIhN4DlIuqlM1vCUMUFQAAAABAQEBAQEBAQEBAQEBAQEBpqYAoPBwPoAwIDUAWMIQAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gBGTlZEUoBMUTE1NkQxAAAAAAACQQMoARIAAAsBCiAgANs=`，并且添加到配置文件中

每次启动安装程序报错不同，有的时候是直接重启，有的时候像是错误报告打了一半。请问应该如何修正。

**Comment by xxxzc** [comment]
可以试一下最新的 release

**Comment by mahoshojoHCG** [comment]
感谢，终于能用了
