### ISSUE TITLE
There is a middle rate of system halt, maybe the cause is VerbStub.kext?

### ISSUE THREAD

**Issue by ximiTech** [xxxzc/xps15-9570-macos#63]
使用过程中发现系统会有一定几率瘫痪，目前去掉了VerbStub.kext，是它导致的瘫痪么？
我会继续试用一下。

**Comment by xxxzc** [comment]
Can you confirm this? VerbStub is providing a audio verb command service, you can replace it with CodecCommander, or just remove it and uninstall ComboJack, and change layout-id to 30 (this may work).

**Comment by ximiTech** [comment]
I changed layout-id to 30, the sound works fine, with and without an earphone.
I changed the original NVME to other ssd, and using an intel ssd to install the hackintosh. Today I reinstall Catalina 10.15.7 without using NVMEfix.kext and VerbStub.kext, the system works fine, no crash now.

**Comment by xxxzc** [comment]
My headphone will be distorted after a few minutes in battery mode if I use layout-id 30, so I have to add those stuff. The latest AppleALC includes a verb command service, I'll see how to use it when I have time.
