### ISSUE TITLE
Can not boot, stuck on after picker

### ISSUE THREAD

**Issue by shyeom79** [xxxzc/xps15-9570-macos#67]
Thanks for your contribution

I have a problem to boot with opencore 0.6.4 intel wifi for Big Sur

using your EFI for opencore 0.6.4 for intel
XPS 9570 with intel wifi AX200, i5-8300H, 4K monitor, intel AX200 wifi, WD Black ssd 1TB, 16RAM, latest bios

Istuck on 34:970 00:025 AAPL: #[EB.B.WFDW|!WF] Err(0xE) 0
34:997 00:026 AAPL: #[EB|LOG:DT] 2020-12-09T18:28:16
35:116 00:119 AAPL: #[EB|LOG:EXITBS:START] 2020-12-09T18:28:16

I am uploading debug log file

please help me

thanks in advance

[opencore-2020-12-09-182741.txt](https://github.com/xxxzc/xps15-9570-macos/files/5670848/opencore-2020-12-09-182741.txt)

**Comment by xxxzc** [comment]
please try this config:
[config.plist.zip](https://github.com/xxxzc/xps15-9570-macos/files/5670937/config.plist.zip)

**Comment by shyeom79** [comment]
thanks so much I will try

**Comment by shyeom79** [comment]
I chagned new config.plist, but nothing changed

uploaded new log file
appreciate it
[opencore-2020-12-10-073603.txt](https://github.com/xxxzc/xps15-9570-macos/files/5671012/opencore-2020-12-10-073603.txt)

**Comment by shyeom79** [comment]
I tried dortania guides Stuck on [EB|#LOG:EXITBS:START]
but still have same problem
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start
[Uploading opencore-2020-12-13-075206.txt…]()

please help me
thanks

**Comment by xxxzc** [comment]
I don't know how to fix it...
