### ISSUE TITLE
UHD630 Finicky HDMI hotplug

### ISSUE THREAD

**Issue by stakeout55** [xxxzc/xps15-9570-macos#69]
Hey everyone, was wondering if someone could shed some light on this for me. So I have my Dell XPS 7590 up and running with BigSur 11.1 and everything appears to be working well except one thing, HDMI hot plugging - to an extent. (Not sure about Thunderbolt haven't tested).

Issue:

When the laptop is booted and logged into BigSur and I plug in the HDMI cable, the machine registers it and my second display works great. No issues. It is when I go to unplug it, the first time I plug/unplug everything works as normal and the laptop recognizes that the HDMI cable was removed and the display changes back to just the laptop screen. The second time I plug/unplug the laptop doesn't recognize that I disconnected the HDMI cable and remains thinking that there are two screens still. (All settings and such allows me to configure the second screen like it is still there even though it is unplugged. I can also move applications off of the laptop screen to where the "second screen would be" and they will stay there like it is still plugged in.) I'll attach a link to my config. Any help would be great.

Config: https://drive.google.com/file/d/1QXBsZaYFGTUIhyY3YZhMA3b1fK1fkSzw/view?usp=sharing

Hardware:

Laptop model: Xps 15 7590 4k IPS, 16gb RAM, 512gb ssd, dual boot with windows 10 pro
CPU: i7 9750h
GPU: uhd 630
Audio codec: Realtek 298, works with layout-id 30
Bios: 1.8.1, offsets changed for undervolt and cfg-lock
Install method: Opencore 0.6.4

**Comment by xxxzc** [comment]
Are you using TypeC? Anyway, 7590 needs following patch to fix TypeC:

```
<dict>
			<key>Comment</key>
			<string>Rename XHC_ to XHC2 in TbtTypeC</string>
			<key>Enabled</key>
			<true/>
			<key>Find</key>
			<data>gkkgWEhDXwg=</data>
			<key>OemTableId</key>
			<data>VGJ0VHlwZUM=</data>
			<key>Replace</key>
			<data>gkkgWEhDMgg=</data>
			<key>TableSignature</key>
			<data>U1NEVA==</data>
		</dict>
```

**Comment by stakeout55** [comment]
Hey I am using standard hdmi. I will still apply this patch for Type C so thank you!

**Comment by Drowningfish223** [comment]
Did you fix the hotplug issue?
