### ISSUE TITLE
Touch Screen Big Sur

### ISSUE THREAD

**Issue by LeoK75** [xxxzc/xps15-9570-macos#72]
Hi,

Any one got the touchscreen working with the latest release?

Cheers

**Comment by xxxzc** [comment]
No. You can use the VoodooI2C（2.5.2） and SSDT-I2CX in release 201208 to enable touchscreen, but it will make touchpad works bad.

**Comment by LeoK75** [comment]
Thank you, got it to work. BTW, did you or anyone get the intel wireless to work? Mine was working in Catalina but not working in Big Sur. It is the Intel Wireless AX card

**Comment by xxxzc** [comment]
you need to replace AirportItlwm, see my readme

**Comment by LeoK75** [comment]
Thank you, I used the 1.1.0 Stable Big Sur version but it hangs at the apple logo and does not boot. only when i switch back to the one in your release version and it will boot but Wifi does not work
