### ISSUE TITLE
How to swap CMD and ALT on latest EFI release?

### ISSUE THREAD

**Issue by adityahota** [xxxzc/xps15-9570-macos#77]
I noticed that as of the last two releases, the physical Windows key is now CMD and the physical ALT key is now CMD. Is there a way to change this so that the ALT key on the keyboard (next to space) maps to CMD in macOS and the Windows key maps to ALT?

**Comment by imraan-go** [comment]
You can do it in System preferences> Keyboard> Modifier Keys

**Comment by adityahota** [comment]
Thanks! That is a good workaround and it also works for my USB keyboard.
