### ISSUE TITLE
Beware with Combojack Patch, it comes with a malware!

### ISSUE THREAD

**Issue by techsnakebo** [xxxzc/xps15-9570-macos#78]
Beware with the Combojack audio fix

Combojack patch have a malware in VerbStub.kext, this was detected using the last version of cleanmymac app
The malware basically uses your Hackintosh PC to mine bitcoin for someone.

I replaced the combojack patch with this other

**https://github.com/xxxzc/xps15-9570-macos/blob/master/README.md** (see the section Headphone https://github.com/xxxzc/ALCPlugFix-Swift/releases/tag/v1.0)

The last statement of that patch is "remove VerbStub.kext in kext folder" this is the kext from your EFI partition, also you should remove VerbStub.kext section from your config.plist

After doing this, the CPU load dropped down from 25-30% to 8-9% in idle mode, the free RAM memory increased dramatically, and stopped the battery drain

**Comment by imraan-go** [comment]
verbstub source code is available in the github repository if you wanna build it yourself. I don't think it has a malware in it, It could be false positive. Again you can build the kext from the source code with Xcode if you want.

**Comment by xxxzc** [comment]
Combojack(VerbStub) do not comes with a malware, you can review the source code https://github.com/hackintosh-stuff/ComboJack/tree/master/VerbStub_Source. The high cpu usage may be caused by an incompatible layout-id.
