### ISSUE TITLE
Adding Smoother Backlight Transitions

### ISSUE THREAD

**Issue by adityahota** [xxxzc/xps15-9570-macos#79]
I saw this over on the X1 Carbon Hackintosh repo.. is this something we could implement in this EFI? It's not necessary, just a user experience enhancement.

https://github.com/hieplpvip/AppleBacklightSmoother

**Comment by imraan-go** [comment]
Just gave it a try but it's not working. Just stuck at lowest brightness.

**Comment by adityahota** [comment]
Hmm okay. Did you also recompile and replace the SSDT-PNLF?

**Comment by imraan-go** [comment]
> Hmm okay. Did you also recompile and replace the SSDT-PNLF?

yes tried that too.Same result.

**Comment by xxxzc** [comment]
I have tried it before，not working
