### ISSUE TITLE
安装(或恢复模式)过程中无法使用触摸板的处理

### ISSUE THREAD

**Issue by M69W** [xxxzc/xps15-9570-macos#8]
~~尝试使用：[VoodooInput](https://github.com/acidanthera/VoodooInput/releases)~~
以上没作用

**Comment by xxxzc** [comment]
因为我把 VoodooPS2Controller 里的 VoodooPS2Mouse.kext 和 VoodooPS2Trackpad.kext 删了，VoodooInput 需要这两个 kexts

**Comment by M69W** [comment]
> 因为我把 VoodooPS2Controller 里的 VoodooPS2Mouse.kext 和 VoodooPS2Trackpad.kext 删了，VoodooInput 需要这两个 kexts

加上这两个驱动对现有OC 有影响吗

**Comment by xxxzc** [comment]
我测试 VoodooPS2Mouse 会影响 MOS.app，VoodooPS2Trackpad 未知，但毕竟用了 VoodooI2C，还是删了好些

**Comment by M69W** [comment]
> 我测试 VoodooPS2Mouse 会影响 MOS.app，VoodooPS2Trackpad 未知，但毕竟用了 VoodooI2C，还是删了好些

这种情况有鼠标可以忽视👌

**Comment by xxxzc** [comment]
新的 VoodooI2C 好像解决了这个问题？
