### ISSUE TITLE
BrcmPatchRam: uploadFirmware could not open the device! 

### ISSUE THREAD

**Issue by d3myz** [xxxzc/xps15-9570-macos#80]
Hi All, Not sure if this is the right place to put this , but I'm looking to switching my currently build to this one, due to support for Big Sur and migrating to OpenCore. I'm currently running the BavarianCake's build for the 9570 that uses Clover. I upgraded to Catalina a few months ago and after the most recent security update hosed my Bluetooth and  i'm getting an error that BCRMPatchRAM cannot open the device (screenshot below).  Also, in regards to switching over to OpenCore, how does one go about migrating? Can I updated my current working build or is it something I have to completely start over with. I'm barely competent to keep my current build running, so maybe it's not a good idea. I haven't been able to find any BigSur builds that use clover.  

Any help or advice would be gladly welcomed and thanks in advance. 

<img width="1480" alt="Screen Shot 2021-01-17 at 1 57 58 PM" src="https://user-images.githubusercontent.com/50464405/104856290-1b094900-58cf-11eb-93e4-b09381fdc6c6.png">

**Comment by xxxzc** [comment]
1. Delete all third-party kexts that you have installed in /Library/Extensions and /System/Library/Extension (like Brcm* in your screenshot)
2. Try my configuration.

I love CLOVER but I gave up to use CLOVER on Big Sur.

**Comment by d3myz** [comment]
Thank you! I am not versed with code and i'm really worried i'll hose my install if I switch over. So you are saying delete all 3rd party kexts from my /Library/Extensions and /System/Library/Extension and BT should work, or delete them and then try your build to migrate? Can I migrate or do i need to just start with a clean build?

**Comment by imraan-go** [comment]
I'm using Dell DW1830 card and my bluetooth works fine until sleep. After waking up, bluetooth does not work properly.

**Comment by xxxzc** [comment]
What do you mean 'migrate'? Clover and OpenCore can coexist. You can just put OpenCore folder to your EFI and add OpenCore.efi as boot entry in BIOS.

But first thing first, please delete those third-pary kexts in L/E and S/L/E, these kexts should be placed only in kext folder in your bootloader. I can‘t guarantee that Bluetooth works, as I said in my README.

**Comment by d3myz** [comment]
Ok, I deleted the 3rd party kexts, I'm a little which files I use to put into my EFI. This XPS15-9570-OC-BRCM-210110 or This xps15-9570-macos-210110? or do I just grab the OC folder out of one of them and add it to my EFI folder? I know how to add it to the boot entry. Sorry, Like I said, i'm not very good at this, but i'm trying.

**Comment by xxxzc** [comment]
Use the OC folder in XPS15-9570-OC-BRCM-210110

**Comment by d3myz** [comment]
I did that, booted from the config and the system gets stuck on the apple logo and the processor fan kicks on and off etc. i'm running mojave, do I need to upgrade to big sur first?

**Comment by d3myz** [comment]
Sorry, currently running Catalina, not Mojave.
