### ISSUE TITLE
ALCPlugFix-Swift doesn't detected microphone from headphone

### ISSUE THREAD

**Issue by imraan-go** [xxxzc/xps15-9570-macos#82]
The goold old combojack used to give us options to use the attached headphone's mic, but the new ALCPlugFix-Swift does not have that. Is it possible to modify and enable it?

**Comment by jaromeyer** [comment]
I've tried pretty much everything. The only solution was to use layout-id 72 with [this fork of ComboJack](https://github.com/lvs1974/ComboJack)
