### ISSUE TITLE
my wifi card  intel 9260ac work on  big sur the net speed so slow but it on catalina in highspeed

### ISSUE THREAD

**Issue by xyhs2018** [xxxzc/xps15-9570-macos#83]
who can tell me why ,I use the last version OC from this page

**Comment by xyhs2018** [comment]
append  my pc 4k screen  i7 8750h intel 9260ac

**Comment by shasen1235** [comment]
The latest Itlwm alpha build just released with 40Mhz support.
Now my AX200 max speed goes up to 150Mb/s from 35Mb/s.

**Comment by M69W** [comment]
need to update [itlwm](https://github.com/OpenIntelWireless/itlwm/releases)
