### ISSUE TITLE
Incorrect battery wear reading

### ISSUE THREAD

**Issue by shasen1235** [xxxzc/xps15-9570-macos#85]
I bought this laptop from second hand for about two months ago.

Before the purchase I checked on the battery capacity and it was about 90%

After two months of normal usage(Never discharge below 30%), the capacity drops down to 75%.

I was thinking, well, maybe the battery is really wearing out.

So I ordered a new battery and did a quick replacement, capacity went back up 100%.

But then within the following one week, I've been monitoring the capacity and it degrades day by day.

At the end of the weekend, just in one week it went from 100% to 85%.

I know Li-Ion battery wears even when storaged, but down to 85% in one week is not acceptable for a new battery.

So I called the dealer and they agreed to send me a new battery.

Last week I received the new replacement and this time it is being manufactured in January 2020.

After replacing for the second time, the capacity went back to 100% again.

But just two days later I found that system is reporting battery cycle went from 0 to 30 again!(Same as the first new battery)

I checked on the original DSDT, and all battery info are already 8 bits so it should be fine leaving untouched according to the tutorial on OpenCore site.

Now I don't know what to do, searching on the net there's not many similar issue reported, maybe people just don't aware of the problem or do we need more patches on this laptop?

Or maybe it's the BIOS's fault? I'm currently on 1.18.

If anyone has similar issue, please share your experience, thanks!

**Comment by imraan-go** [comment]
This is pretty common for third party batteries. You can change the charging rate from BIOS to "Always plugged in" or "Normal". Anyway, this is not related to this EFI or hackintosh in general.

**Comment by shasen1235** [comment]
Thank you for your comment.
But this behaves the same in the first party battery that comes with the laptop.
(The previous owner used it for 2 years and gets 10% wears and I got 15% by just 2 months)
I will try changing the setting and boot on Windows only for a few day and see if it's a platform problem.

One thing that made me think it's a Hackintosh problem is that switching between ACPIBatteryManager and SMCBatteryManager resorts in differenct battery cycle and wearing.

**Comment by imraan-go** [comment]
Don't trust the battery reporting in hackintosh.It's not reliable. You can boot into windows and execute cmd: "powercfg /batteryreport" . This will report battery usage and other details.

**Comment by shasen1235** [comment]
I did hear from some users saying Hackintosh battery report is not reliable and I can accept that if its what it is. 
However, on my 9570 once the max capacity is updated on Hackintosh, reboot to Windows then generate report by ”powercfg /batteryreport” shows the same wear level.
That makes me wonder if SMCBatteryManager.kext handles battery info in an improper way? 
I own many mobile devices but I’ve never seen one‘s battery wear out this fast.

===Update===
The issue persists on WIndows as well, maybe it's a BIOS problem.
Downgraded to 1.16 and see if it helps.

===Update2===
Downgrade to 1.16 seems to do the work! No battery wear during past 3 days.
I know normally Li-Ion battery shouldn't degrade in just a few days.
But before downgrade mine did everyday even plugged all the time.
Will give more time to test but if new BIOS was truly the cause, Dell needs to get their things together:/
