### ISSUE TITLE
Modify SMCDellSensors to slow down CPU fans ？

### ISSUE THREAD

**Issue by tofuliang** [xxxzc/xps15-9570-macos#87]
Even CPU temperature is lower than 50℃, the fan is still running at about 2500RPM.
Found some lead about minimum speed here [VirtualSMC](https://github.com/acidanthera/VirtualSMC/blob/032a0f6c8731ca3cd1f349e93fb1463b71b8d558/Docs/iStat.txt#L1857) ,
Can we modify VirtualSMC to slow down the fan？

**Comment by Drowningfish223** [comment]
if you disable smcdellsensors.kext the fans start up later
