### ISSUE TITLE
Dual Boot Windows

### ISSUE THREAD

**Issue by romancin** [xxxzc/xps15-9570-macos#9]
Thank you very much for this repo, OpenCore working flawlessly here on a 7590 15 inch 4k here. I have only one thing to solve for the momento. Is It possible to dual Boot Catalina and Windows? I have tried selecting Windows 10 inside Catalina Boot disk preferences but It always Boot macOS. Thank you!

**Comment by xxxzc** [comment]
Yes, I can dual boot Windows and Catalina.

You should specify Windows bootloader path in `config.plist>Misc>BlessOverride`, for me is `\EFI\Microsoft\Boot\bootmgfw.efi`, then you can boot Windows by select `BOOTCAMP Windows` on OC menu.

**Comment by romancin** [comment]
Thank you very much @xxxzc 
The problem was that I didn't keep Microsoft folder on EFI when changing Clover with your OpenCore prepares one. Solved. Thank you very much!
