### ISSUE TITLE
dell m5530感谢好用的efi，能否修改cpu为正确的i7-8850h，触摸屏能驱动吗

### ISSUE THREAD

**Issue by txb2d** [xxxzc/xps15-9570-macos#95]
dell m5530作为xps9570的同门师兄地，我抱着试试看态度使用了您的efi，几乎完美驱动bigsur11.5
现在问题是cpu不能正确显示为我的i7-8850h
我是4k触摸屏，这一个也不能驱动能否通过i2c定制实现呢？
感谢好用的efi，能否修改cpu为正确的i7-8850h，触摸屏能驱动吗？期待您的回复

**Comment by txb2d** [comment]
我用的是最新版本210610 intel 网卡版本！我想问一下如何开启触摸屏（没有触摸屏太难受了），还有如何设置我正确的cpu为i7-8850h。期待您的回复！！！！

**Comment by xxxzc** [comment]
1. cpu 处理器频率和核心数显示正常吗？不影响睿频就没啥关系，可以用 [hackintool](https://github.com/headkaze/Hackintool) 看看cpu型号对不对
2. 触摸屏试试把 SSDT-I2CX 换成这个
[SSDT-I2CX.zip](https://github.com/xxxzc/xps15-9570-macos/files/6871835/SSDT-I2CX.zip)

**Comment by txb2d** [comment]
> 1. cpu 处理器频率和核心数显示正常吗？不影响睿频就没啥关系，可以用 [hackintool](https://github.com/headkaze/Hackintool) 看看cpu型号对不对
> 2. 触摸屏试试把 SSDT-I2CX 换成这个
>    [SSDT-I2CX.zip](https://github.com/xxxzc/xps15-9570-macos/files/6871835/SSDT-I2CX.zip)

<img width="1191" alt="1" src="https://user-images.githubusercontent.com/20257498/126856504-e76f2d23-e7d1-4a05-bfc6-eacfff9682d4.png">
<img width="1191" alt="2" src="https://user-images.githubusercontent.com/20257498/126856516-32dcd88b-ceb6-42c5-80a6-96081c1bfd3b.png">
两个地方显示不一样；我的8850h正确参数应该是如下
<img width="574" alt="5" src="https://user-images.githubusercontent.com/20257498/126856551-fa232064-38d7-4612-bafc-3108666c9c54.png">
--------------------------------------
<img width="1191" alt="3" src="https://user-images.githubusercontent.com/20257498/126856562-8c9106ee-3e29-4749-9f57-d4bad9108e97.png">
为什么这地方显示我现在用的oc是0.57！这是什么情况！！！
期待您的回复，等会换一下您给的i2cx看看能否驱动触摸屏，会不会和触摸板冲突！

**Comment by txb2d** [comment]
经过测试SSDT-I2CX.zip可以驱动触摸. 替换后 要在终端执行：python3 update.py --acpi

完美运行！！！感谢感谢啦！！！！！！！！

**Comment by txb2d** [comment]
<img width="668" alt="1" src="https://user-images.githubusercontent.com/20257498/126883965-2f93c626-d717-47c7-9b69-dbd7888ed410.png">
电池调节都是灰色怎么回事？都不能调节的吗？

**Comment by williamoak1988** [comment]
> 经过测试SSDT-I2CX.zip可以驱动触摸. 替换后 要在终端执行：python3 update.py --acpi
> 
> 完美运行！！！感谢感谢啦！！！！！！！！

您好，为何还要运行一下python这个代码呀，如果不运行，触摸屏能用吗？
