### ISSUE TITLE
MacOS monterey update?

### ISSUE THREAD

**Issue by imraan-go** [xxxzc/xps15-9570-macos#99]
Any plan to update the EFIs to support macOS 12.0.1 ?

**Comment by xxxzc** [comment]
No update planned recently, I haven't used macOS for a long time.

**Comment by itsundef** [comment]
Will update the update.py later, for now use this, updated to OC 0.7.4 and Kexts. Also yes, WiFi/Bluetooth works on Intel cards.
 
[https://github.com/itsundef/xps15-9570-macos/releases/tag/211102](https://github.com/itsundef/xps15-9570-macos/releases/tag/211102)

**Comment by thespacemanatee** [comment]
@itsundef Is there any difference other than updated kexts? Our current EFIs should work right if it's working with Big Sur already. Have you tested if the camera works on Monterey?

**Comment by itsundef** [comment]
@thespacemanatee Yes, config.plist has new entries under UEFI->Driver and other places as well. Yes, everything works out of the box, infact I fresh installed it from recovery and with verbose disabled I straight up ended to setup screen.

**Comment by thespacemanatee** [comment]
@itsundef  hmm then why not just make a pull request instead haha

**Comment by itsundef** [comment]
> @itsundef hmm then why not just make a pull request instead haha

If you look at the release notes, it does say I have removed the update.py, the thing is I never noticed the fact that config.plist was generated from the script until I updated to OC > 0.7.0. As for pull request, will do once I update the script, also if you want you can run diff on both the configs and update the script, I won't mind. 🙃

**Comment by xxxzc** [comment]
Uploaded
